### ISSUE TITLE
Segmentation fault (core dumped) when trying to run pod5 convert fast5

### ISSUE THREAD

**Issue by DepledgeLab** [nanoporetech/pod5-file-format#103]
Hello,

I'm running into a 'Segmentation fault (core dumped)' error every time I try to run pod5 convert fast5 but I cannot figure out why. 

I have set POD5_DEBUG=1 but this is not providing any additional information, nor can I find a log file. I was interpreting this as a memory error but I have requested a single CPU with 128Gb memory which surely should be sufficient?

D

**Comment by HalfPhoton** [comment]
@DepledgeLab ,
Can you please provide the command you used?

Kind regards,
Rich

**Comment by DepledgeLab** [comment]
Ah, I'm sure I meant to do that in the first post!

pod5 convert fast5 fast5_pass/*.fast5 --output pod5 --one-to-one fast5_pass/

I also tried it without the one-to-one fast5_pass/ option but had the same result

**Comment by HalfPhoton** [comment]
And you're on the latest `pod5 --version`?

**Comment by DepledgeLab** [comment]
I'm on version 0.2.4 (which I think is the latest based on running pip install --upgrade pod5)

**Comment by HalfPhoton** [comment]
Interesting  - `0.2.4` is not the latest - Can you try and upgrade to [0.3.2](https://pypi.org/project/pod5/)?

**Comment by DepledgeLab** [comment]
Curious. Which version of Python is needed for 0.3.2? I have been using v3.8.6 but can't seem to upgrade to a higher version of pod5 with this

**Comment by HalfPhoton** [comment]
Pod5 is available on all actively supported python versions 3.8->3.12 
Can you share what error you're seeing while trying to upgrade?

**Comment by DepledgeLab** [comment]
Ach. Fool that I am I just realized the wrong python version (3.7) was being loaded into the environment... I've replaced this with 3.10 and now everything runs just fine.

Apologies for being dim

**Comment by HalfPhoton** [comment]
@DepledgeLab ,

No worries at all! Happy to get you back up and running again!

Best regards,
Rich
