### ISSUE TITLE
V0.3.6 pod5 view "Error while processing"

### ISSUE THREAD

**Issue by roo-weed** [nanoporetech/pod5-file-format#106]
On pod5 version 0.3.6, I get the following error message when trying to run `pod5 view`:
`POD5 has encountered an error: 'Error while processing 'pod5/FAW15801_3cbced68_8a8d5a01_880.pod5'`
I thought my files were corrupted, so I tried copying them over from my backup again-- no luck. When I downgrade back to V0.2.4, however, pod5 view works just fine on the same files. Would love any guidance about this and happy to provide files for testing if necessary. 
Thanks!
-Roo

**Comment by HalfPhoton** [comment]
Hi @roo-weed, 

Could you please send us the log files generated from running:
```POD5_DEBUG=1 pod5 view <your command>``` 

Kind regards,
Rich

**Comment by HalfPhoton** [comment]
@roo-weed , please see the solution for #107.

**Comment by roo-weed** [comment]
@HalfPhoton thanks so much for this quick solution!
