### ISSUE TITLE
pod5 webserver memory error

### ISSUE THREAD

**Issue by ranitori** [nanoporetech/pod5-file-format#108]
Hello,
I have been using the pod5 converter at pod5.nanoporetech.com successfully for some time now. However, recently it no longer processes .fast5 files, and comes up with a "memory access out of bounds" error.
Do youy know how this can be fixed?
Thanks

**Comment by 0x55555555** [comment]
Hi @ranitori,

Have you tried passing the same data in as you did before, or is it new data?

We haven't made any changes to the site.

Thanks,
- George

**Comment by ranitori** [comment]
Hi George,
Thanks for the reply. I have not, but i tried some additional new data and it did work. It seems that I may just have some corrupt .fast5 files that cause the issue.
Thanks, Roberto
