### ISSUE TITLE
Stable access to read.reader.schema.metadata in the Python API

### ISSUE THREAD

**Issue by tbooth** [nanoporetech/pod5-file-format#11]
Hi,

In my software, it is useful to have access to the POD5 file format version. It's possible, but not via the public API.

Old version:

`p5_handle._read_reader.reader.schema.metadata[b'MINKNOW:pod5_version']`

Current version:

`p5_handle._handles.read.reader.schema.metadata[b'MINKNOW:pod5_version']`

The `metadata` dict also contains a file UUID and the name of the software that made the file - both useful too. Would it be possible to make access to this metadata dict part of the public/documented Python API please?

Cheers,

TIM

**Comment by jorj1988** [comment]
Hi Tim,

Those are really great requests - I will get them into the API for the next release.

Thanks,
- George

**Comment by tbooth** [comment]
Thanks @jorj1988! For info, this is my script:

https://github.com/EdinburghGenomics/hesiod/blob/master/get_pod5_metadata.py

Obviously it's not in production yet, but I wanted to get on top of things before actual POD5 files start coming out of our Promethion and I need to make a summary report.

**Comment by jorj1988** [comment]
Hi @tbooth,

This should now be resolved in 0.0.31, see accessors beginning here:

https://github.com/nanoporetech/pod5-file-format/blob/master/python/pod5_format/pod5_format/reader.py#L700

Any feedback would be welcome!

- George

**Comment by tbooth** [comment]
The new accessor is perfect, thank you, but...

I'm getting the version reported as '0.0.35' even with my old test file which is version '0.0.15' (as confirmed by reading the file with hexdump). This value seems to be coming from the C code rather than being a problem with the Python library. I can't see where that number is coming from from a quick look through the C code but then I'm not very good at reading C.

This is with the version installed from PyPi (0.0.41) as I'm being too lazy to compile the GitHub version from source, but let me know if you want me to do further tests or send the sample file in question.

**Comment by jorj1988** [comment]
Hi @tbooth ,

The version thats returned is the fle version held in memory, after any migration steps have occured.

What you're seeing is the file after pod5 loads it and migrates it through any required steps to get to the latest version (which python API requires):

https://github.com/nanoporetech/pod5-file-format/blob/master/c%2B%2B/pod5_format/migration/v2_to_v3.cpp#L121

I have another patch coming shortly which exposes the on disk version of the file. However, if youre trying to key off the version in order to know how to open/manipulate the file - this is the correct version to use.

Thanks,
- George

**Comment by tbooth** [comment]
Thanks for the clarification, @jorj1988. My purpose here is to collect some metadata about the files that are stored on our datastore, or rather to show that we will be able to collect similar metadata from POD5 as we currently do for all the FAST5 files generated here in the facility. I'm not sure how useful this version number will actually be to us - knowing what version of MinKNOW and/or Guppy produced any given file is the key piece of auditing info - but just like the lab here carefully record every lot number of every reagent we tend to take the approach of recording everything we can, just in case.

I'll look out for the upcoming patch. Thanks.

**Comment by jorj1988** [comment]
Right,

the new field is likely to be useful for sure, but you may also want:

https://github.com/nanoporetech/pod5-file-format/blob/master/docs/tables/run_info.toml#L67

the `software` field in the run info struct - itll tell you the version of minknow that wrote the file.

- George
