### ISSUE TITLE
Getting the signal chunk size of a pod5 file

### ISSUE THREAD

**Issue by hiruna72** [nanoporetech/pod5-file-format#118]
Hello,

How can I get the signal chunk size of a pod5 file?

`pod5 inspect summary` does not provide this information.

Thanks.

**Comment by HalfPhoton** [comment]
Hi @hiruna72,
You can use [pod5.reader.ReadRecord.signal_rows](https://pod5-file-format.readthedocs.io/en/latest/reference/api/pod5.reader.html#pod5.reader.ReadRecord.signal_rows) to get this information using the API.

Kind regards,
Rich
