### ISSUE TITLE
pod5 convert fast5 warning: Failed to read key read_XXX

### ISSUE THREAD

**Issue by creaturemoon** [nanoporetech/pod5-file-format#121]
Hello,
    When I used the command `pod5 convert fast5 /path/to/sample/*.fast5 -t 1 -o sample_all.pod5` (pod5 v0.3.10) to convert hundreds of nanopore DRS fast5 files to pod5, I got many warnings like this,

> warnings.warn(
/XX/software/mambaforge/lib/python3.10/site-packages/pod5/tools/pod5_convert_from_fast5.py:580: UserWarning: Failed to read key read_00a6d8e2-c1ad-4148-ae37-23becaea2d8b from //path/to/sample/PAQ48458_pass_e7c8fe0a_d6ff6c63_3463.fast5 : "Unable to synchronously open object (file read failed: time = Fri Mar 29 01:51:10 2024\n, filename = '//path/to/sample/PAQ48458_pass_e7c8fe0a_d6ff6c63_3463.fast5', file descriptor = 16, errno = 5, error message = 'Input/output error', buf = 0x5620af79b1c0, total read size = 512, bytes this sub-read = 512, bytes actually read = 18446744073709551615, offset = 0)" 

Do you know the reason for this and how to solve it?

In addition, when I used one fast5 file to convert like this, `pod5 convert fast5 PAQ48458_fail_bd4e428b_dd773d4e_60.fast5 -t 1 -o PAQ48458_fail_bd4e428b_dd773d4e_60.pod5`, I always got the error no matter which file it is,

> PAQ48458_fail_bd4e428b_dd773d4e_60.fast5 is not a multi-read fast5 file.                                                                                                                         
Converting 1 Fast5s: 0Reads [01:17, ?Reads/s]

But when I viewed the file on the HDFView and used `single_to_multi_fast5`, it turns out it is multi-read. 

> ERROR:ont_fast5_api.conversion_tools.single_to_multi_fast5:Failed to initialise single-read Fast5File: 'PAQ48458_fail_bd4e428b_dd773d4e_60.fast5': Cannot input MultiRead files to single_to_multi: 'PAQ48458_fail_bd4e428b_dd773d4e_60.fast5'
ERROR:ont_fast5_api.conversion_tools.single_to_multi_fast5:Can't decrement id ref count (unable to close file, errno = 5, error message = 'Input/output error')
	Failed to write to MultiRead file: tmp/batch_0.fast5

![image](https://github.com/nanoporetech/pod5-file-format/assets/103840889/fa808347-e40f-4095-ad02-73190450d868)

A fast5 file is uploaded to here, https://www.jianguoyun.com/p/DTifZC0Qm4yVCxjDnbsFIAA , Is there a way to correct the error by changing the content of the fast5 file manually?

Thanks!

**Comment by HalfPhoton** [comment]
Hi @creaturemoon,
The `"is not a multi-read fast5 file"` message might be the incorrect warning here. We issue this warning assuming that the problem if the file cannot be loaded is that it's not a multi-read fast5 but it looks like HDF5/python is having issues loading the file. 
```
'//path/to/sample/PAQ48458_pass_e7c8fe0a_d6ff6c63_3463.fast5', 
file descriptor = 16, 
errno = 5, 
error message = 'Input/output error', 
buf = 0x5620af79b1c0, 
total read size = 512, 
bytes this sub-read = 512, 
bytes actually read = 18446744073709551615,  <<< Erroneously large
offset = 0)"
```

This can be an issue with your file system or a corrupt file. [HDF5 Forum Discussion](https://forum.hdfgroup.org/t/reading-from-a-hdf5-file-using-h5py-fails/9848)

Kind regards,
Rich

**Comment by creaturemoon** [comment]
Hi,
  Thank you for the reply. I restarted the server and it can run normally now.
