### ISSUE TITLE
Troubleshooting Conversion of Fast5 Files to Pod5 Format

### ISSUE THREAD

**Issue by biozzq** [nanoporetech/pod5-file-format#122]
Dear all,

To convert the fast5 files deposited in `warwick.s3.climb.ac.uk/nanopolish_tutorial/methylation_example.tar.gz` to pod5 format, I first converted the single_read_fast5 files to multi_read_fast5 files using the command `single_to_multi_fast5 -i ./fast5_files/ -s ./ -f merge -n 100000`. After checking for issues in the multi_read_fast5 files (using the script methioned here https://github.com/nanoporetech/pod5-file-format/issues/97) and finding none, I attempted to convert the multi_read_fast5 file to pod5 using the command `PDG5_DEBUG=1 pod5 convert fast5 merge_0.fast5 --output output.pod5`. However, i did not receive any output after running the conversion command.

![image](https://github.com/nanoporetech/pod5-file-format/assets/15704257/ee0a7298-fbdc-45b2-945c-dfe7fe794e50)

> Please provide a description of your issue and include any commands used to reproduce the issue.

## Logs

> Please provide any log files.

i did not receive any output after running the conversion command.

## Specifications

- Pod5 Version: Pod5 version: 0.3.10
- Python Version: Python 3.9.7
- Platform: `Linux version 3.10.0-957.el7.x86_64 (root@centos76) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC) ) `

Has anyone else encountered a similar issue?

regards,

Zheng zhuqing

**Comment by HalfPhoton** [comment]
Hi @biozzq,
Can you share the output from the logs? I've noticed that you've misspelled `PDG5_DEBUG=1` - should be `POD5_DEBUG=1`. 

Does `output.pod5` exist at all?

Kind regards,
Rich

**Comment by biozzq** [comment]
Hi @HalfPhoton 

Thank you for your reply. According to your suggestions, there are two log files generated, as shown below. I hope this information can help you solve the problem I am facing. Thank you.
[2024-04-18--12-38-57-main-pod5.log](https://github.com/nanoporetech/pod5-file-format/files/15019958/2024-04-18--12-38-57-main-pod5.log)
[2024-04-18--12-38-58-p-23267-pod5.log](https://github.com/nanoporetech/pod5-file-format/files/15019959/2024-04-18--12-38-58-p-23267-pod5.log)

Regards,
Zheng zhuqing

**Comment by biozzq** [comment]
I found that the `median_before` attribute exists in the single_read_fast5, which can be accessed using h5dump -A single_read_fast5. Also, the multi_read_fast5 file also contains `median_before` attribute.

**Comment by HalfPhoton** [comment]
Are you able to access the "median_before" attribute in python?
Something like this might help you explore the issue. This snippet is trying to reproduce where [the error is ](https://github.com/nanoporetech/pod5-file-format/blob/3da54259cf42d656a7332e2867fffb4c25e36a0f/python/pod5/src/pod5/tools/pod5_convert_from_fast5.py#L551)according to the logs. 



```python
from h5py import File
with File(str(f5_path), "r") as f5:
  read_ids = [k for k in f5.keys() if k.startswith("read_")]
  for read_id in read_ids:
    median_before = f5[read_id]["Raw"].attrs["median_before"]
    print(f"{read_id} median_before: {median_before}")
```

**Comment by biozzq** [comment]
Yes, it will give me following error. What is the reason for this problem? Do you have a solution? Thank you very much.

`Other exception: 'Unable to synchronously open object (invalid identifier type to function)' from: merge_0.fast5`

Regards,
Zheng zhuqing

**Comment by HalfPhoton** [comment]
Can you share some more information about the content of the file? Something like this might be helpful to deduce what the difference might be between what's expected versus reality.

```python
from h5py import File
with File(str(f5_path), "r") as f5:
  read_ids = [k for k in f5.keys() if k.startswith("read_")]
  for read_id in read_ids:
    print(f"{read_id=}")
    print(f"{f5[read_id]=}")
    print(f"{f5[read_id]['Raw']=}")
    print(f"{f5[read_id]['Raw'].attrs=}")
```

**Comment by HalfPhoton** [comment]
Also - can you re-create the multi-read fast5 incase there was an issue during conversion?

**Comment by biozzq** [comment]
Here is the file information based on your suggestion. 

<img width="717" alt="image" src="https://github.com/nanoporetech/pod5-file-format/assets/15704257/e8931325-29d8-43c3-830c-5757685d5d5a">

**Comment by HalfPhoton** [comment]
Everything looks like it's working here - can you try and delete any problematic reads?

**Comment by biozzq** [comment]
Thank you for your assistance. Can you please advise me on how to remove the problematic reads from a fast5 file? Additionally, should I perform the processing from a single_read_fast5 file or a multi_read_fast5 file?
