### ISSUE TITLE
error：XX.fast5 is not a multi-read fast5 file

### ISSUE THREAD

**Issue by moxqiang** [nanoporetech/pod5-file-format#123]
## Issue Description

I used the following command to convert fast5 to pod5：
`data_dir="/public/home/qqfu/Rawdata/20230421-HML230364-P6-PAO32024-sup/fast5_pass"
out_dir="/public/home/qqfu/fast5Topod5/20230421-HML230364-P6-PAO32024-sup"
/public/home/yuanhuisun/miniconda3/envs/ont-meth/bin/pod5 convert fast5 $data_dir/*.fast5 --output $out_dir --one-to-one $data_dir -t 12
echo "finish"`

There's a file that shows a failure
`/public/home/qqfu/Rawdata/20230421-HML230364-P6-PAO32024-sup/fast5_pass/PAO32024_pass_e2b825a7_77e8dc86_2581.fast5 is not a multi-read fast5 file.`

I have noticed that some researchers have encountered the same problem

https://github.com/nanoporetech/pod5-file-format/issues/75

I tried to solve the problem using the "single_to_multi_fast5" method.
But it was unsuccessful and the following message is displayed:
` Cannot input MultiRead files to single_to_multi`
Does this mean there is no problem with my file?

Thank you!

## Specifications

- Pod5 Version:0.3.10
- Python Version:3.8.19
- Platform:2.6.32-504.el6.x86_64

**Comment by HalfPhoton** [comment]
The error `is not a multi-read fast5` can mask other issues such as simply not being able to open the file or it being corrupt in some other way. We'll try and improve the error messaging around this area as it comes up frequently.

Please omit this problematic file and continue. 

Kind regards, 
Rich

**Comment by moxqiang** [comment]
Dear Rich,

Thank you very much for your quick reply and explanation. I understand the problem you mentioned and will follow your suggestion.

Thank you again for your help and patience.
