### ISSUE TITLE
Lost signal data

### ISSUE THREAD

**Issue by atongmuuu** [nanoporetech/pod5-file-format#128]
Lost signal data after converting pod5 file to fast5 file

**Comment by HalfPhoton** [comment]
Can you be more specific with your issue please?

**Comment by atongmuuu** [comment]
I converted the pod5 file to fast5 with the `pod5 convert to_fast5` command and then used HDFView to view the fast5 file, where `Singal` had no data.
![image](https://github.com/nanoporetech/pod5-file-format/assets/62009236/b238f0f0-822e-4e3b-b63b-13424934152a)

Next, I use the `multi_to_single_fast5` command to generate a single fast5 file. Similarly, there is no `Signal` data in a single fast5 file, but there is `Events` data. I don't know if this is normal.
![image](https://github.com/nanoporetech/pod5-file-format/assets/62009236/7a84d962-c0b2-48e8-9935-588632ec7c88)

![image](https://github.com/nanoporetech/pod5-file-format/assets/62009236/ca8feb26-5d11-4026-858f-7d771dd82d3a)

Here is one of the fast5 files.
[test.zip](https://github.com/nanoporetech/pod5-file-format/files/15430942/test.zip)
