### ISSUE TITLE
Maintain input folder hierarchy on conversion to/from fast5

### ISSUE THREAD

**Issue by olawa** [nanoporetech/pod5-file-format#13]
Hi,

I would like to convert a large set of old minion runs to pod5 for long term storage and possibly re-basecalling. By default only one pod5 file is created and when I try  --output-one-to-one each fast5 is converted to a separate pod5 but placed in the same folder. I got the error below, likely because files in pass/fail folders have the same name. Would be great if either folder structure could be kept or pass/fail added to file names, and also if the conversion keeps track of read id:s to remove duplicates, as I think is done in guppy and in the single_to_multi fast5 conversion tool.

An unexpected error occurred: Input path already exists. Refusing to overwrite.

Traceback (most recent call last):
  File "/home/minion/anaconda3/bin/pod5-convert-from-fast5", line 8, in <module>
    sys.exit(main())
  File "/home/minion/anaconda3/lib/python3.7/site-packages/pod5_format_tools/pod5_convert_from_fast5.py", line 623, in main
    args.signal_chunk_size,
  File "/home/minion/anaconda3/lib/python3.7/site-packages/pod5_format_tools/pod5_convert_from_fast5.py", line 603, in convert_from_fast5
    raise exc
  File "/home/minion/anaconda3/lib/python3.7/site-packages/pod5_format_tools/pod5_convert_from_fast5.py", line 565, in convert_from_fast5
    writer = output_handler.get_writer(item.file)
  File "/home/minion/anaconda3/lib/python3.7/site-packages/pod5_format_tools/pod5_convert_from_fast5.py", line 395, in get_writer
    return self._open_writer(output_path=output_path)
  File "/home/minion/anaconda3/lib/python3.7/site-packages/pod5_format_tools/pod5_convert_from_fast5.py", line 381, in _open_writer
    writer = p5.Writer(output_path)
  File "/home/minion/anaconda3/lib/python3.7/site-packages/pod5_format/writer.py", line 84, in __init__
    raise FileExistsError("Input path already exists. Refusing to overwrite.")
FileExistsError: Input path already exists. Refusing to overwrite.

**Comment by jorj1988** [comment]
Hello - it seems like you already have files in the output location, or alternatively files named the same thing in your input?

Can you show me the tree of files you are trying to convert in the input/output, and the exact command you are running?

Thanks,
- George

**Comment by olawa** [comment]
Hi, yes files in the input are named the same, that was the point I was making. It is (was?) done so by default when minknow splits reads into fast5_fail and fast5_pass.

I couldn't find any documentation on if it is better to keep 4000 reads/file or if it is better to store more reads per pod5 file?

**Comment by olawa** [comment]
In this case input files are named like this:
20191118_1537_MN19470_FAK64715_2f44e93d/fast5_fail/FAK64715_3b9c09954054f5908e63cf500553a769d9b98cea_0.fast5
20191118_1537_MN19470_FAK64715_2f44e93d/fast5_pass/FAK64715_3b9c09954054f5908e63cf500553a769d9b98cea_0.fast5

So I assumed this is what caused the error but it could also be from duplicated folders.

**Comment by olawa** [comment]
Ok, thanks. Having too many reads per file was a problem for some tools with fast5 but perhaps this is one of the reasons for the format being replaced. For large runs it may still be better to split reads into multiple files, so would be good if there was an option to define how many reads to store per pod5 file.

**Comment by jorj1988** [comment]
Hi @olawa,

Please try the latest release, where the conversion scripts now have `--file-read-count` as an option, and to maintain the input folder hierarchy.

- George
