### ISSUE TITLE
Question / Feature Request: Appending reads to an existing file with pod5.Writer

### ISSUE THREAD

**Issue by denisbeslic** [nanoporetech/pod5-file-format#138]
Hi,

I’m currently working with the pod5.Writer and I’m wondering if there’s an option to append a set of reads to an existing file instead of creating a new one.

Here’s a snippet of my current approach:
```
pod5_reads = []

        for idx, (read_id, signal) in enumerate(self.signals.items()):
            [...]
            read = pod5.Read(
                read_id=uuid4(),
                pore=pore,
                calibration=calibration,
                read_number=idx,
                start_sample=0,
                median_before=median_before_value,
                end_reason=end_reason,
                run_info=run_info,
                signal=signal_raw,
            )
            pod5_reads.append(read)

with pod5.Writer(self.filename) as writer:
    for read in pod5_reads:
        writer.add_read(read)   
```

I would like to know if it's possible to modify the pod5.Writer or use it in such a way that it allows appending reads to an existing .pod5 file. Currently, pod5.Writer creates a new file, but my goal is to append data to an existing one.

Is there a built-in feature or recommended approach to achieve this?

Thanks for your help!

**Comment by 0x55555555** [comment]
Hi @denisbeslic,

There isn't currently direct API to do this, you could write a new file then merge them together (using pod5 merge) to achieve the same end result?

Thanks,
- George

**Comment by denisbeslic** [comment]
Hi George,
thanks for the suggestion. That should work for now.
