### ISSUE TITLE
About potential MinKNOW output

### ISSUE THREAD

**Issue by hasindu2008** [nanoporetech/pod5-file-format#15]
how will the MinKNOW output be - what would be the default batch size? 
And, also is MinKNOW going to output one large single POD5 file per one sequencing run or will it be multiple POD5 files like it Is being done with FAST5 at the moment?

**Comment by jorj1988** [comment]
Hi @hasindu2008 ,

Good questions - theyll be answered with the upcoming release of minknow!

- George
