### ISSUE TITLE
POD5 complete uninstalling on Ubuntu machine

### ISSUE THREAD

**Issue by DenisGoryunov** [nanoporetech/pod5-file-format#151]
Hi,

Because of the absence of `POD5 conda package`, i tried to install `POD5` using pip in the new `conda environment`, but occasionally make to steps, which i'd like to `UNDO`:

1. From my `conda ENV`, i ran systemwide `pip` installation
2. I installed `POD5` by `pip install pod5` command

How i can completely uninstall both `pip` and `POD5`, including all `dependencies` and `trace files` from my `Ubuntu` system? Could you help me please? After `pip` and `POD5` removing i'd like to reinstall `POD5` but with `pip` installed locally in my `conda ENV`.

Regards,
Denis

**Comment by 0x55555555** [comment]
Hi @DenisGoryunov ,

You can remove pod5 using ```> pip uninstall pod5```.

How did you install pip? You will need to use the instructions that came with the pip install instructions you used.

Thanks,
- George

**Comment by DenisGoryunov** [comment]
Hi George,

Thanks for your reply! Will `pip uninstall pod5` command completely remove all dependencies and trace files as well? I've installed `pip` by `sudo apt install python3-pip` command.

Regards,
Denis

**Comment by HalfPhoton** [comment]
No - `pip uninstall pod5` will not uninstall pod5's dependencies that we're installed alongside pod5. 

If you're going to uninstall pip then I suppose the following will just uninstall **everything** currently installed.

```bash
pip list | awk '{print $1}' > requirements_to_uninstall.txt
pip uninstall -r requirements_to_uninstall.txt
```

As for uninstalling pip itself.. 
```bash
sudo apt remove python3-pip
```

Kind regards,
Rich

**Comment by DenisGoryunov** [comment]
Hi Rich,
Thank you very much! Your solution works for me, but i had to add egrep in the pipe:
`pip list | awk '{print $1}'| egrep -v '^-' > requirements_to_uninstall.txt`
Otherwise i got the error:
`ERROR: Invalid requirement: ----------------------`
`pip: error: no such option: ----------------------
In addition i got a number of warnings:
`Found existing installation: wadllib 1.3.6
Not uninstalling wadllib at /usr/lib/python3/dist-packages, outside environment /usr
Can't uninstall 'wadllib'. No files were found to uninstall.
Found existing installation: wheel 0.37.1
Not uninstalling wheel at /usr/lib/python3/dist-packages, outside environment /usr
Can't uninstall 'wheel'. No files were found to uninstall.
Found existing installation: xkit 0.0.0
Not uninstalling xkit at /usr/lib/python3/dist-packages, outside environment /usr
Can't uninstall 'xkit'. No files were found to uninstall.
Found existing installation: zipp 1.0.0
Not uninstalling zipp at /usr/lib/python3/dist-packages, outside environment /usr
Can't uninstall 'zipp'. No files were found to uninstall.
Found existing installation: zope.interface 5.4.0
Not uninstalling zope-interface at /usr/lib/python3/dist-packages, outside environment /usr
Can't uninstall 'zope.interface'. No files were found to uninstall.`
`I'm just wondering, if it's ok?

**Comment by HalfPhoton** [comment]
No problem, 

Some of those packages might be part of pip itself as pip is written in python afterall. So it should be ok.

Best regards,
Rich
