### ISSUE TITLE
Installation on macOS

### ISSUE THREAD

**Issue by AngusNano** [nanoporetech/pod5-file-format#16]
Hi,

I'm having difficulties installing pod5 on macOS Ventura. When I use `pip install pod5` I get the following error:
`ERROR: Cannot install pod5==0.0.43 and pod5==0.1 because these package versions have conflicting dependencies.`

The same command on Ubuntu 20.04.5 works fine.

Cheers,

Angus

**Comment by jorj1988** [comment]
Hi Angus,

Can you confirm what architecture your mac is running?

Also, what version of python are you running (source of the distribution too)? is it a universal python?

Thanks,
- George

**Comment by AngusNano** [comment]
Hi George,

I'm running an M1 Max with python 3.9.12 (Anaconda).

Thanks,

Angus

**Comment by jorj1988** [comment]
Hi @AngusNano,

Please give the 0.1.4 release a try - we have fixed this issue!

- George
