### ISSUE TITLE
Julia library for accessing POD5 data

### ISSUE THREAD

**Issue by chofski** [nanoporetech/pod5-file-format#19]
Are there any plans to expand the list of languages able access POD5 data files? I'd be particularly interested in a Julia package?

Given the completeness of the Python package (which is brilliant for scripting), merely having the ability to load and extract data from a POD5 data file using other languages would be sufficient. There is no need for options to manipulate or write out the data to new files. From the Julia perspective this should be fairly trivial given that [Arrow.jl](https://arrow.juliadata.org/dev/manual/#User-Manual) can do the heavy lifting with the data tables, but I couldn't from the documents figure out how you have wrapped these up in the container.

Happy to put in some effort to get this off the ground as it would remove another dependancy in my workflows and working with HDF5 is horrid. I'd like to make the jump ASAP!

Thanks, Tom.

**Comment by jorj1988** [comment]
Hi @chofski ,

Assuming Julia can open the pod5 shared library, you should be able to open the file with `pod5_open_file` and call `pod5_get_file_read_table_location` to locate the sub-file which arrow itself can open. From there, as you say you can use arrow bindings to handle the file as with any normal arrow file.

Hope that helps,
Thanks,
- George

**Comment by chofski** [comment]
I'll give it a go. Thanks.
