### ISSUE TITLE
Training a basecaller

### ISSUE THREAD

**Issue by chrishendra93** [nanoporetech/pod5-file-format#20]
I am trying to train a basecaller with the raw signals saved in pod5 format. Does the team have any best practices with regard to accessing the read individually from a single output.pod5 file? Currently I am using this with Pytorch so when defining a dataset object, each read is accessed individually and each time we will call:

    with p5.Reader(fpath) as read:
        read = next(read.reads([read_id]))

is this the most efficient way to access a single read from the reader object?

Thanks!

**Comment by jorj1988** [comment]
> is this the most efficient way to access a single read from the reader object?

No, it likely isn't.

I can't tell for sure without looking at more of your code, but you may be opening the file each time you need to access 1 read?

You should cache the file handle, and iterate a list of reads within that file at once - that will allow pod5 to iterate the file as efficiently as possible.

_However_ if youre in the early stages of development, and doing lots of work outside POD5, you may not see this a significant performance issue, and it may be easier to leave it as is - I would recommend you run some benckmarking and optimise when required.
