### ISSUE TITLE
pod5 inspect reads format to match the needs for pod5 subset

### ISSUE THREAD

**Issue by Kirk3gaard** [nanoporetech/pod5-file-format#21]
Ideally the pod5 tool guides would include an example on generating a summary file based on a folder with pod5s and then subsequently subset based on the channel information to facilitate easier duplex calling. https://github.com/nanoporetech/dorado/issues/68#issuecomment-1401993662

I am struggling a bit with the formats and I am not sure that what is called summary by pod5 subset is even the same file as is output from pod5 inspect reads. 

From the guides:
pod5 inspect reads https://github.com/nanoporetech/pod5-file-format/blob/master/python/pod5/README.md#pod5-inspect-reads
"Inspect all reads and print a csv table"

pod5 subset https://github.com/nanoporetech/pod5-file-format/blob/master/python/pod5/README.md#subsetting-from-a-summary
"pod5 subset can dynamically generate output targets and collect associated reads based on a tab-separated file "

I tried to convert the csv file from pod5 inspect to tab using csvkit and provide that file as summary but that gave me the following error "Number of passed names did not match number of header fields in the file"

What I tried to run:
`
# get summary information from pod5 reads
pod5 inspect reads pod5_original/*pod5 > summary.csv

# Convert list to tsv format
csvformat -T summary.csv > summary.tsv

# subset based on channel
pod5 subset pod5_original/*pod5 --output barcode_channel_subset --summary summary.tsv --columns channel --template "{channel}.subset.pod5"
`

**Comment by jorj1988** [comment]
Hi @Kirk3gaard ,

Thanks for this, we will take a look internally now!

- George

**Comment by Kirk3gaard** [comment]
Temporary fix using R on the summary file from "pod5 inspect reads"
## R code
```r
# Load library
library(tidyverse)
# load summary file from pod5 inspect reads
data<-read_csv("summary.csv",skip = 1)
# Create a column with filenames based on sequencing channel and 
# write a csv file with columns for filenames and read_id
data %>%
  mutate(filename=paste0("pod5_out_ch_",channel,".pod5")) %>%
  arrange(channel) %>%
  select(filename,read_id) %>%
  write_csv(file = "file_for_sorting_by_channel.csv",col_names = F)

```
## Pod5 subset command
`pod5 subset pod5_original/*pod5 --output channel_subset/ --csv file_for_sorting_by_channel.csv`
