### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by RenscoHogers** [nanoporetech/pod5-file-format#27]
I have been trying to install this tool in order to convert my fast5 files into pod5 files.
Unfortunately, every time I use the conan build command, as described in #5, I get the following error:
`ERROR: Error loading conanfile at '/lustre/nobackup/WUR/ABGC/hoger006/Tools/pod5-file-format/conanfile.py': Unable to load conanfile in /lustre/nobackup/WUR/ABGC/hoger006/Tools/pod5-file-format/conanfile.py
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/lustre/nobackup/WUR/ABGC/hoger006/Tools/pod5-file-format/conanfile.py", line 3, in <module>
    from conans import CMake, ConanFile, tools
ImportError: cannot import name 'CMake' from 'conans' (/home/WUR/hoger006/lustre_dir/Tools/mambaforge/envs/conan/lib/python3.11/site-packages/conans/__init__.py)
`
Because I am trying to install this tool on an HPC, I do not have administrative access, which might cause this error to occur.

Is there a package which contains a pre-built version of this tool, or a containerised version?

For reference I cloned the github and am using conan version 2.0.2 through mamba/conda.

**Comment by HalfPhoton** [comment]
Hi @RenscoHogers

Could you please try with ``pip install "conan<2" `` ?

Also, are you not able to directly install via ``pip install pod5`` ?

Hopefully this resolves your issue and I'll emphasise the conan version limit in the documentation:

https://pod5-file-format.readthedocs.io/en/0.1.11/docs/install.html#developing-with-conan

Rich

**Comment by RenscoHogers** [comment]
Hi Rich,

Thank you for your suggestions, downgrading conan to an early version seems to have worked!
