### ISSUE TITLE
broken pipe error when running pod5

### ISSUE THREAD

**Issue by Flower9618** [nanoporetech/pod5-file-format#28]
Hi, when I try to run pod5 v0.1.13 to convert .fast5 to .pod5, there is an error:
![image](https://user-images.githubusercontent.com/77596901/227729920-5741d987-5468-4f1b-bcc6-0114c1c0cb72.png)

Anyone has some advice? Thank you very much!

**Comment by Flower9618** [comment]
I run dorado ... && touch one log file. Interestingly, although there is an error about broken pipe, the log file is created. I would like to know whether dorado succeed or failed?

**Comment by HalfPhoton** [comment]
Hi @Flower9618, from the command it looks like you're running `pod5 convert fast5` and it appears to have raised this error right at the very end. As the conversion step looks like it's finished, could you check that all of the pod5 files which were generated here are complete, running `pod5 inspect summary` over the outputs. 

To help us with tracking down this error, could you share with us; 
- The full command was run
- Your operating system
- The `pod5 --version` 



We'll look into this issue now.

Thanks

**Comment by HalfPhoton** [comment]
Thanks for reporting this issue.
We've isolated this bug and are issuing a fix in `0.1.14` imminently.

**Comment by HalfPhoton** [comment]
This issue should now be resolved in the latest `0.1.15` release.

Thanks again for reporting this issue.

Best regards,
Rich

**Comment by maxim-h** [comment]
For people that may still stumble on a similar problem. I've been running `pod5 convert fast5` with `--one-to-one` option and got the `BrokenPipeError` as well.
Turns out that the output directory contained some files from a previous interrupted run. Clearing the output directory from any files solved the issue.
