### ISSUE TITLE
Understanding the signal_row count and the POD5 writing

### ISSUE THREAD

**Issue by hasindu2008** [nanoporetech/pod5-file-format#3]
Hi,

Could you please help me to  understand what is happening behind the following piece of code (that I got from Dorado's POD5 reading):

```
            if (pod5_get_signal_row_info(file, signal_row_count, signal_rows_indices,
                                        signal_rows.data()) != POD5_OK) {
                fprintf(stderr,"Failed to get read %ld signal row locations: %s\n", row, pod5_get_error_string());
            }

            fprintf(stderr,"ROw count\t%s\t%ld\n", read_id_tmp, signal_row_count);

            size_t total_sample_count = 0;
            for (size_t i = 0; i < signal_row_count; ++i) {
                total_sample_count += signal_rows[i]->stored_sample_count;
            }

            int16_t *samples = (int16_t*)malloc(sizeof(int16_t)*total_sample_count);
            size_t samples_read_so_far = 0;
            for (size_t i = 0; i < signal_row_count; ++i) {
                if (pod5_get_signal(file, signal_rows[i], signal_rows[i]->stored_sample_count,
                                   samples + samples_read_so_far) != POD5_OK) {
                }

                samples_read_so_far += signal_rows[i]->stored_sample_count;
            }
```

Is this `signal_row_count` the number of chunks the MinKNOW is expecting to write when directly writing? However, when I converted 500,000 reads from fast5 to pod5, none of the reads has other than 1 for signal_row_count. When MinKNOW is writing files, what would be the expected value for this signal_row_count? I am asking this because the [primary design goal in POD5](https://github.com/nanoporetech/pod5-file-format/blob/master/docs/DESIGN.md) has been writing (and the need to write in chunks) and thus if the converter is not producing a file that the MINKNOW is expecting to produce, none of the reading-related benchmarks we do using pod5 generated using fast5 conversion are representative of the reality, as seek system calls (or major page faults if mmap is used internally) are ignored. If MinKNOW is expecting to reconvert chunked POD5 to unchunked POD5, then the benchmarks would be still representative, but if such a conversion is done, it contradicts the need to have a 'balanced' file format.

Also, are there any benchmarks done to evaluate POD5's writing performance? And is there a C API to do POD5 writing?.

Thank you.

**Comment by hasindu2008** [comment]
Have these chunk-related parameters for writing in POD5 during a live run been determined now? 
I am waiting for those so that I could do a benchmark for a chunked BLOW5 approach suggested by @lh3 on Twitter a few months ago. It would interesting to compare the writing speed of a simple file format like BLOW5 compared to a complex format like POD5.

**Comment by jorj1988** [comment]
MinKNOW is intending to use the default chunk size when writing pod5 files, yes.

**Comment by hasindu2008** [comment]
Looks like the above-mentioned strategy for BLOW5 with that default chunk size you mentioned for POD5 seems to be able to handle 32 positions (32*3000channels) on my laptop and 72 (72*3000channels)  on a gaming desktop, based on a quick simulation I wrote over a couple of days during the Christmas break. This is a simulation of a highly multithreaded environment that mimics the acquisition of chunks, writing and reading for basecalling that I wrote based on the limited information I know about MinKNOW. Do you have any such writing benchmarks for POD5 that I could run on my laptop and see?

**Comment by jorj1988** [comment]
Hi @hasindu2008, we dont have those sorts of benchmarks available in the repository - its a good idea. We may consider adding them in future - alternatively if you have something you'd like to contribute we would welcome it!

Thanks,
- George

**Comment by vellamike** [comment]
Closing this issue because I understand the initial question around understanding `signal_row count` and the POD5 writing is resolved.
