### ISSUE TITLE
pod5 merge error "too many open files"

### ISSUE THREAD

**Issue by CWYuan08** [nanoporetech/pod5-file-format#30]
Hi, I tried to merge all the pod5 files for one sample (>8k files) but encountered this: 

POD5 has encountered an error: '[Errno 24] Too many open files'

For detailed information set POD5_DEBUG=1'

What should I try next? Should I use cat to merge the files directly? Many thanks!

Best,
CW

**Comment by HalfPhoton** [comment]
Hi @CWYuan08 , are you using the most recent version of pod5?

This issue was addressed in a recent release.

Kind regards,
Rich

**Comment by HalfPhoton** [comment]
Hi @CWYuan08 , is this issue resolved?

Kind regards,
Rich

**Comment by CWYuan08** [comment]
Dear @HalfPhoton, 

yes! This has worked, thank you very much!

Best,
CW
