### ISSUE TITLE
pod5 convert fast5 stuck at checking fast5 stage

### ISSUE THREAD

**Issue by billytcl** [nanoporetech/pod5-file-format#32]
(pod5 0.1.16, python 3.7.13)

I have a folder of ~7000 fast5 files that I want to convert into pod5. From running --help, I am using this command:

```
usage: pod5 convert fast5 [-h] -o OUTPUT [-r] [-t THREADS] [--strict]
                          [-O ONE_TO_ONE] [-f]
                          [--signal-chunk-size SIGNAL_CHUNK_SIZE]
                          inputs [inputs ...]

Convert fast5 file(s) into a pod5 file(s)

positional arguments:
  inputs                Input path for fast5 file

optional arguments:
  -h, --help            show this help message and exit
  -r, --recursive       Search for input files recursively (default: False)
  -t THREADS, --threads THREADS
                        Set the number of threads to use [default: 10]
                        (default: 10)
  --strict              Immediately quit if an exception is encountered during
                        conversion instead of continuing with remaining inputs
                        after issuing a warning (default: False)

required arguments:
  -o OUTPUT, --output OUTPUT
                        Output path for the pod5 file(s). This can be an
                        existing directory (creating 'output.pod5' within it)
                        or a new named file path. A directory must be given
                        when using --one-to-one. (default: None)

output control arguments:
  -O ONE_TO_ONE, --one-to-one ONE_TO_ONE
                        Output files are written 1:1 to inputs. 1:1 output
                        files are written to the output directory in a new
                        directory structure relative to the directory path
                        provided to this argument. This directory path must be
                        a relative parent of all inputs. (default: None)
  -f, --force-overwrite
                        Overwrite destination files (default: False)
  --signal-chunk-size SIGNAL_CHUNK_SIZE
                        Chunk size to use for signal data set (default:
                        102400)

**nohup pod5 convert fast5 -o pod5/CHM13.pod5 --recursive --strict -t 60 multi_fast5/ &**
```

When I check nohup, I'm getting this:

```
cat nohup.out
Checking Fast5 Files:   0%|          | 0/7469 [00:00<?, ?Files/s]
```

Using ps, I'm getting the following status codes -- I believe indicating it's waiting for something to finish:
```
ps ux
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
billylau 3471706  1.5  0.0 19561020 308316 pts/12 Sl  15:19   0:32 /home/billylau/.conda/envs/pod5/bin/python /home/billylau/.conda/envs/pod5/bin/pod5 convert fast5 -o pod5/CHM13.pod5 --recursive --strict -t 60 multi_fast5/
billylau 3472653  0.0  0.0   8892  3280 pts/12   R+   15:55   0:00 ps ux
```

top also indicates that nothing is happening:
```
PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                                                                                                                                                   
3471706 billylau  20   0   18.7g 311000  42388 S   2.0   0.0   0:34.00 pod5
```

It's been like this for ~30 minutes now with nothing updating. When I look at the code, eg. https://github.com/nanoporetech/pod5-file-format/blob/73617c63ac310cc4e9f8d23cf06f2bfde5d21b7b/python/pod5/src/pod5/tools/pod5_convert_from_fast5.py, it doesn't look like it's doing anything more than checking whether they are multi or not and it should update the progress bar quickly.                                                                       

Edit: doing a single pod5 file works fine:
```
nohup pod5 convert fast5 -o pod5/CHM13.pod5 --recursive --strict -t 60 multi_fast5/FAK50913_c7ef4ac6a67eb7bce6220608fccf5b19227f4904_5.fast5 &

cat nohup.out
Converting 1 Fast5s: 100%|##########| 4000/4000 [00:11<00:00, 352.08Reads/s]
```                                                                               

Edit 2: adding a wildcard to the input seems to make it "not stuck", but it still seems absurdly slow to me on the checking step:
```
nohup pod5 convert fast5 -o pod5/CHM13.pod5 --recursive --strict -t 60 multi_fast5/*
Checking Fast5 Files:  12%|#2        | 920/7469 [20:50<8:54:48,  4.90s/Files]
```

It seems like it's fast at first but then slows down in the first minute:

```cat nohup.out
Checking Fast5 Files:   0%|          | 0/7469 [00:00<?, ?Files/s](pod5) billylau@suzuki:/mnt/ix1/Projects_lite/20230403_BL_CHM13_nanopore_raw/00_fast5$ cat nohup.out
Checking Fast5 Files:   6%|5         | 425/7469 [00:13<03:03, 38.39Files/s](pod5) billylau@suzuki:/mnt/ix1/Projects_lite/20230403_BL_CHM13_nanopore_raw/00_fast5$ cat nohup.out
Checking Fast5 Files:   7%|6         | 512/7469 [00:16<03:15, 35.58Files/s](pod5) billylau@suzuki:/mnt/ix1/Projects_lite/20230403_BL_CHM13_nanopore_raw/00_fast5$ cat nohup.out
Checking Fast5 Files:   7%|6         | 512/7469 [00:16<03:15, 35.58Files/s](pod5) billylau@suzuki:/mnt/ix1/Projects_lite/20230403_BL_CHM13_nanopore_raw/00_fast5$ cat nohup.out
Checking Fast5 Files:   7%|6         | 512/7469 [00:16<03:15, 35.58Files/s](pod5) billylau@suzuki:/mnt/ix1/Projects_lite/20230403_BL_CHM13_nanopore_raw/00_fast5$ cat nohup.out
Checking Fast5 Files:   8%|7         | 566/7469 [00:23<05:25, 21.21Files/s](pod5) billylau@suzuki:/mnt/ix1/Projects_lite/20230403_BL_CHM13_nanopore_raw/00_fast5$ cat nohup.out
Checking Fast5 Files:   8%|7         | 566/7469 [00:23<05:25, 21.21Files/s](pod5) billylau@suzuki:/mnt/ix1/Projects_lite/20230403_BL_CHM13_nanopore_raw/00_fast5$ cat nohup.out
Checking Fast5 Files:   8%|7         | 566/7469 [00:23<05:25, 21.21Files/s](pod5) billylau@suzuki:/mnt/ix1/Projects_lite/20230403_BL_CHM13_nanopore_raw/00_fast5$ cat nohup.out
Checking Fast5 Files:   8%|7         | 584/7469 [00:40<14:34,  7.87Files/s](pod5) billylau@suzuki:/mnt/ix1/Projects_lite/20230403_BL_CHM13_nanopore_raw/00_fast5$ cat nohup.out
Checking Fast5 Files:   8%|7         | 584/7469 [00:40<14:34,  7.87Files/s](pod5) billylau@suzuki:/mnt/ix1/Projects_lite/20230403_BL_CHM13_nanopore_raw/00_fast5$ cat nohup.out
Checking Fast5 Files:   8%|7         | 584/7469 [00:40<14:34,  7.87Files/s](pod5) billylau@suzuki:/mnt/ix1/Projects_lite/20230403_BL_CHM13_nanopore_raw/00_fast5$ cat nohup.out
Checking Fast5 Files:   8%|7         | 593/7469 [00:50<23:56,  4.79Files/s]
```

**Comment by HalfPhoton** [comment]
Hi @billytcl , 
Thank you for the detailed report on this issue.

We'll look into this and get a fix out as soon as we can.

If this is blocking your work, an interim solution would be to convert files in batches (say ~500 fast5s) and merge the outputs if you need one monolithic output. 

Thanks again for bringing this to our attention.

Kind regards,
Rich

**Comment by billytcl** [comment]
Just to clarify a bit on what I'm doing: I'm trying to turn the CHM13 T2T nanopore data into pod5. When I download their raw files, there's a bunch that are single read fast5s that I use ont_fast5_api to turn into multis (eg. single_to_multi_fast5 -i untar/ -s multi_fast5/single_big/ -f single_merge --recursive -t 60). It appears that pod5 really doesn't like these files when I try to do a batch convert using pod5 convert (as I said before, singles seem to be ok). Their premade fast5s work totally fine.

**Comment by HalfPhoton** [comment]
Thanks for the additional update @billytcl  this is really helpful.

Just to clarify one point, can you convert to pod5, any converted single-read to multi-read fast5 files at all? Even one at a time?

If these converted single -to-multi-read fast5s are causing the checker threads to han, then it would explain why the checker made some progress and then slows to a stop as each thread comes across one of these files.

Kind regards,
Rich

**Comment by billytcl** [comment]
I can confirm that I can do one at a time by specifying the exact multi-fast5 that I want to convert. I've almost finished creating a bunch of individual pod5s that I will merge.

Narrowing it down a bit further, I think that the initial checking step is just really slow, and for large numbers of fast5 files (eg. 6000 in this case) the progress bar doesn't update well. Checking ~600 multi fast5s (the ones that already came as multi) from the T2T dataset took over an hour to check with the progress bar working. Thus, the remainder of the T2T single_to_multi converted files (~7000) would take >10x longer. 

I was probably thinking it was hanging because the CPU usage is so low during these steps. I'm guessing that the h5py library is just not very good for checking. My impression is that testing to see whether a file is a multi or not should take less than 1 second but looking at the code it looks like it goes through a few more checks.

**Comment by billytcl** [comment]
OK, so I've narrowed down the bottleneck.

I'm not 100% certain, but I believe it's a bug on ont_fast5_api. Newer files return "multi-read" on the file_type attribute. But older ones don't, such as the CHM13 T2T multi files and surprisingly even ones that are generated from single_to_multi from ont_fast5_api.

The second bug is an issue with h5py. Referencing https://github.com/nanoporetech/pod5-file-format/blob/73617c63ac310cc4e9f8d23cf06f2bfde5d21b7b/python/pod5/src/pod5/tools/pod5_convert_from_fast5.py#L220, both the if len(_h5) == 0 and if any(key for key in _h5 if key.startswith("read_")) are really slow when reading a fast5 file for the first time. Looks like it traverses the entire file to get all the keys first instead of just doing a regular iterator. I'm not sure if there's an easy way to fix this one, as opposed to setting the file_type tag correctly.

**Comment by HalfPhoton** [comment]
@billytcl ,

`0.1.19` has moved the file-checking stage into the conversion processes so it shouldn't hold you up as much.

We're looking into patching `ont_fast5_api` to correctly set the `file_type` attribute to also improve performance.

**Comment by HalfPhoton** [comment]
z

**Comment by HalfPhoton** [comment]
Closing this issue as it will be fixed in `ont_fast5_api`.
