### ISSUE TITLE
Error processing message when running pod5 convert fast5

### ISSUE THREAD

**Issue by Flower9618** [nanoporetech/pod5-file-format#34]
Hi, when I run pod5 convert fast5 command, I will get this message after this command run a while:
`Sub-process trace: `
`A process in the process pool was terminated abruptly while the future was running or pending.`

I do not know the reason and also do not know how to solve this question. Thank you very much!

**Comment by sklages** [comment]
it may be related to #33 

Can you check how large your dataset is and whether there is enough diskspace available (in the working directory)?

**Comment by Flower9618** [comment]
Hi, @sklages . Thank you for your reply.
It seems not the memory or disk problem. 
This is the detail about the error. When converting 30%, the speed is fast. But when converting 80%, the speed is quite slow, and when I `top`, there is no pod5 command running.
<img width="1501" alt="image" src="https://user-images.githubusercontent.com/77596901/232958052-258029bc-f590-4438-92bb-7b292b1b61ef.png">
![image](https://user-images.githubusercontent.com/77596901/232958093-ecc41e23-921c-4a6a-82f7-4c1ce7fcbac3.png)

**Comment by sklages** [comment]
@Flower9618 - the same here. And you're right, it's not a disk space issue. After all I came to the same conclusion. #33

**Comment by Flower9618** [comment]
Hi, @sklages .
Thank you very much. I see. So it seems even if I set the `--threads 1`, it will not work. The only way to do it is breaking fast5 files into chunks...but this is inconvenient for large amounts of data...:(

**Comment by HalfPhoton** [comment]
Thanks for bringing this to our attention. 

There are a number of changes to convert fast5 which are review which should hopefully improve performance. Including removing the initial multi-read fast5 check stage.

Thank you for your patience with us while we resolve these issues.

We'll let you know as soon as we get a tagged release out.

Kind regards,
Rich

**Comment by Flower9618** [comment]
@HalfPhoton .
Thank you so much. I am looking forward to it.

**Comment by HalfPhoton** [comment]
@Flower9618, I'm pleased to say we released `0.1.19` last night, which should contain fixes for your issue. Could you please give it a go and let us know if this patch has resolved your issues?

Kind regards,
Rich

**Comment by Flower9618** [comment]
@HalfPhoton , thank you so much. I will try it. :)

**Comment by Flower9618** [comment]
Hi, @HalfPhoton 
I try `pod5 convert fast5` command on the same sample as before, and  it runs successfully. Thank you very much !

**Comment by HalfPhoton** [comment]
@Flower9618 , I'm very happy to hear that! Thanks for letting us know that it's fixed 😃 

Thanks again,
Rich
