### ISSUE TITLE
'An unexpected error occurred: Trying to re-open a closed Writer to ... ' when running pod5 convert fast5

### ISSUE THREAD

**Issue by Flower9618** [nanoporetech/pod5-file-format#35]
Hi, when I run `pod5 convert fast5` command, I got this error when running 74% of the process :
`An unexpected error occurred: Trying to re-open a closed Writer to ... .pod5`

**Comment by HalfPhoton** [comment]
Hi @Flower9618 ,

Sorry I didn't spot this issue sooner. This is an unexpected error where an output file has been marked complete and is closed but is then re-opened which would overwrite the outputs. 

Can you share your full command? Are you using `--strict`?

Could you re-run the same application with `POD5_DEBUG=1 pod5 convert fast5 <args>` and share the log files that were generated?

**Comment by Flower9618** [comment]
I do not know why the error happen, but when I rerun the command, there is no error. Thank you so much.

**Comment by HalfPhoton** [comment]
Hi @Flower9618 ,

Thanks for responding and closing the issue. 

I believe I've found the source of this issue. It will be patched in the next release.

Kind regards,
Rich
