### ISSUE TITLE
pip install doesn't give any results for pod5

### ISSUE THREAD

**Issue by callumparr** [nanoporetech/pod5-file-format#39]
```
❯ pip install --upgrade pod5
ERROR: Could not find a version that satisfies the requirement pod5 (from versions: none)
ERROR: No matching distribution found for pod5
```

**Comment by HalfPhoton** [comment]
Hi @callumparr ,

Was system are you running on? It seems from your next issue that you were able to install `pod5` eventually is that correct?

Kind regards,
Rich

**Comment by callumparr** [comment]
Hey, I tried originally in my base conda environment that runs Python 3.6.10. 

I then activated another environment I used to install xpore and Python 3.8 and I could use pip install to get pod5 working. 

I guess just the original error messaging from conda wasn't helpful.
