### ISSUE TITLE
KeyError: 'sample_id'

### ISSUE THREAD

**Issue by sachingadakh** [nanoporetech/pod5-file-format#42]
Hi,
I am trying to convert fast5 files to pod5 to perform base-calling and modification calling using Dorado,  on the nanopore-wgs-consortium NA12878 dataset. But I am getting the KeyError: 'sample_id'. 
I was getting some sort of error as  "can't locate attribute: 'sample_id' error." while I was using Bonito for base-calling and modification calling.
Is there something I can do to make it work or to debug the issue?

**Comment by HalfPhoton** [comment]
Hi @sachingadakh,

It appears as though the dataset that you' are trying to convert has removed some or all of the `tracking_data` attributes which include `sample_id` on [L869](https://github.com/nanoporetech/pod5-file-format/blob/4ff85d09e46c8551b303d1330fdc116dabe178d0/python/pod5/src/pod5/tools/pod5_convert_from_fast5.py#L469) 

We will look into setting a default value in these cases where an attribute is missing as a long term fix. 

To unblock your work before we patch this,  you may be able to set missing attributes manually on a local copy of the dataset using `h5py`. The pod5 convert tools could be used as a reference on which attributes are require and how to create them.

Alternatively,  you can install the pod5 tools from source and edit the line referenced above to set a default value. 

```python
#from
sample_id=decode_str(tracking_id["sample_id"])
#to
sample_id=decode_str(tracking_id.get("sample_id", b"unknown"))
```

Thanks for raising this issue with us, we will implement a long term fix soon.

Kind regards, 
Rich

**Comment by sachingadakh** [comment]
Hello Richard,
  Thank you for the response and, most importantly alternative solution to continue my work. The editing line in "pod5_convert_from_fast5.py" script worked for me and further enabled Dorado to work for base and modification calling.
I am closing this issue.
