### ISSUE TITLE
Guppy v6.5.7 with pod5 uses tons of memory vs fast5

### ISSUE THREAD

**Issue by billytcl** [nanoporetech/pod5-file-format#45]
I converted fast5s to a ~900 GB single pod5 file (v0.2). When basecalling, it is taking up a ton of memory:

<img width="636" alt="image" src="https://github.com/nanoporetech/pod5-file-format/assets/10386511/5ced4a40-ffac-47c2-b0e2-84f8086d190b">

This doesn't happen when I call from fast5s. Is this normal?

**Comment by jorj1988** [comment]
Hi @billytcl,

This is due to how pod5 uses virtual memory, it's to do with how data is cached in case its needed again.

Does the basecall run ignoring the high memory use?

We will look at changing config to avoid this memory usage.

Thanks,
- George

**Comment by billytcl** [comment]
As long as it won't crash the system then it's all good!

**Comment by jorj1988** [comment]
Hi @billytcl,

It's OS managed, so will be released once another process needs the memory. It should be harmless, but I agree it can look worrying.

- George
