### ISSUE TITLE
Fast5 to pod5 - 5khz mode

### ISSUE THREAD

**Issue by gwl2** [nanoporetech/pod5-file-format#46]
ONT changed the sampling mode to 5khz recently.

I think I remember that the pod5 format was also developed to be able to save this kind of data. 

By accident the format of the raw reads was changed from pod5 to fast 5 for one of our runs. Now I am not sure, if i convert the fast5 to pod5 afterwards, is the resulting pod5 file real 5khz sampled data, or was it lost/reduced to 4 khz due to the initial fast5 format.

Note I'll also post this question on the dorado github, as I am not sure which site is correct for this issue.

**Comment by jorj1988** [comment]
Hi @gwl2,

Both formats can store 5KHz data, you can safely convert between the two.

Your files will be smaller when compressed in pod5 (this will depend somewhat on read length and data in the files), but a fast5 file with 5KHz data is still valid to basecall.

- George

**Comment by gwl2** [comment]
Great thanks!
