### ISSUE TITLE
Support for parquet storage?

### ISSUE THREAD

**Issue by willros** [nanoporetech/pod5-file-format#47]
Hi,

I wonder if there is any support to store pod5 file in Apache parquet format?

Thanks,
William

**Comment by jorj1988** [comment]
Hi @willros ,

Parquet is a different disk format to Pod5, so there isnt direct support for writing a pod5 to parquet.

You could read the data out and write it as parquet, but it'll be a different format.

Can you tell me more about your application?

Thanks,
- George

**Comment by willros** [comment]
Yes, I know it is a different format. 

Me and my colleagues are having a discussion about how archive sequencing data for long term storage. Since pod5 is based on Apache Arrow I thought that converting the pod5 files to parquet files could be a good way to save some disk space for long term storage. 

I tried to find some more information or other people implementing this, but could not find anything, hence the opening of this issue. 

Thanks for the answer! 
William

**Comment by jorj1988** [comment]
No worries,

Pod5 already uses compression on the signal portion of the data - this provides a significant saving against the raw data. The compression is custom designed for our signal format to provide a good compression ratio while still being able to compress/decompress quickly.

I'm not aware of parquet having better compression techniques available than what we use - but I may be out of date.

Thanks,
- George

**Comment by Psy-Fer** [comment]
Hey, our team made and support the slow5 format, and in the course of our work we investigated some other compression methods. You can find them on some some branches on our repo if you are interested. 

bottom line is, the extra effort and resources isn't really a good trade off compared to the current methods used here by pod5 (slow5 uses very similar).

Using zstd for meta data and svb-zd for signal is pretty damn good. Of course if there is some new method you wanna try, it might work well to implement as a pull request to pod5 (or slow5 of that's more to your liking).

Cheers.
James

(p.s. Hope you don't mind the commentary George)

**Comment by willros** [comment]
Thank you @Psy-Fer and @jorj1988 for your answers! Very helpful! 

William

**Comment by jorj1988** [comment]
Not at all @Psy-Fer - all good advice.

https://github.com/lemire/streamvbyte is the basis of integer compression all these projects use originally. as @Psy-Fer  says we use zstd over the top of a streamvbyte-like compression.

- George
