### ISSUE TITLE
Missing `pod5_format_export.h` ?

### ISSUE THREAD

**Issue by huicongyao** [nanoporetech/pod5-file-format#48]
Hi, I tried to find `pod5_format_export.h` in this project, but it is missing. But your other cpp files have included it many times, where is it?

**Comment by jorj1988** [comment]
Hello,

This file is generated as part of the build process, please see steps here: [theonetruenerd](https://github.com/nanoporetech/pod5-file-format/blob/master/docs/docs/install.rst#developing).

Thanks,
- George
