### ISSUE TITLE
pod5:Enqueueing exception with pod5 convert

### ISSUE THREAD

**Issue by masohn** [nanoporetech/pod5-file-format#49]
I want to convert my single_read_fast5 files into multi_read_fast5_file(s) into one .pod5 file.
```
single_to_multi_fast5 -i {input} -s {output}
pod5 convert fast5 {output}/*.fast5 --output converted.pod5
```
where {input} is simply the folder with all the single-read fast5 files.

The command single_to_multi_fast5 converts my input files into a file "batch_0.fast5" and additionally it outputs a "filename_mapping.txt".

But when I try to use the pod5 command, the following error appears:
```
Converting 1 Fast5s:   0%|   | 0/4000 [00:00<?, ?Reads/s]ERROR:pod5:Enqueueing exception: batch_0.fast5 'sample_id'
Converting 1 Fast5s:   0%|   | 0/4000 [00:00<?, ?Reads/s]
WARNING:pod5:Unfinished exceptions found during shutdown!
```
I can't do much with the error message, I think maybe something got lost in the conversion that pod5 needs.

I am using the following libraries:
```
pod5 0.2.2 
ont-fast5-api 4.1.1 
```

**Comment by HalfPhoton** [comment]
Hi @masohn ,

I think this is the same as issue https://github.com/nanoporetech/pod5-file-format/issues/42 where the required `sample_id` field is missing in the input data.

We haven't implemented a fix for this as of `0.2.2` but as this issue has reappeared, we'll prioritise this and patch it soon. Please follow the instructions on the linked issue if you need to be unblocked immediately. 

Kind regards,
Rich

**Comment by HalfPhoton** [comment]
@masohn ,

`v0.2.3` has just been released which now handles missing fast5 fields (where possible) substituting an empty string.

Could you give it a try and let us know if you're issue is resolved?

Kind regards,
Rich

**Comment by masohn** [comment]
@HalfPhoton I will try it out and give you a response as soon as possible.
Thank you for your efforts.

**Comment by masohn** [comment]
@HalfPhoton I just tried it and it works, my problem is solved. Thank you for the quick fix.
