### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by OZTaekOppa** [nanoporetech/pod5-file-format#5]
Hi,

I am trying to install this program on HPC (PBSpro) but not sure which part I should follow.
And, I have tried "Developing with conan" and "Pre commit".

FYI, this is what I did.

conda activate pip and cmake

 git clone https://github.com/nanoporetech/pod5-file-format.git
cd pod5-file-format
git submodule update --init --recursive
mkdir build
cd build

conan install --build=missing -s build_type=Release ..
cmake -DUSE_CONAN=ON -DCMAKE_BUILD_TYPE=Release ..

Both attempts were not successful due to the cmake step.

ERROR: boost/1.78.0: Error in build() method, line 875
        self.run(full_command, run_environment=True)
        ConanException: Error 1 while executing b2 -q target-os=linux architecture=x86 address-model=64 binary-format=elf abi=sysv --layout=system --user-config=/home/uqhjung3/.conan/data/boost/1.78.0/_/_/source/source_subfolder/tools/build/user-config.jam -sNO_ZLIB=0 -sNO_BZIP2=0 -sNO_LZMA=1 -sNO_ZSTD=1 boost.locale.icu=off --disable-icu boost.locale.iconv=on boost.locale.iconv.lib=libc threading=multi visibility=hidden link=static variant=release --with-atomic --with-chrono --with-container --with-context --with-contract --with-coroutine --with-date_time --with-exception --with-filesystem --with-iostreams --with-locale --with-log --with-program_options --with-random --with-regex --with-serialization --with-stacktrace --with-system --with-test --with-thread --with-timer --with-type_erasure --with-wave toolset=gcc define=_GLIBCXX_USE_CXX11_ABI=0 pch=on  cxxflags="-fPIC -DBOOST_STACKTRACE_ADDR2LINE_LOCATION=/usr/bin/addr2line" install --prefix=/home/uqhjung3/.conan/data/boost/1.78.0/_/_/package/cf5b1011055d170fc18a05ba048979d2089d1695 -j24 --abbreviate-paths -d0 --debug-configuration --build-dir="/home/uqhjung3/.conan/data/boost/1.78.0/_/_/build/cf5b1011055d170fc18a05ba048979d2089d1695"

Any idea or suggestion on this matter?

Many thanks in advance!

Taek

**Comment by jorj1988** [comment]
Hi @OZTaekOppa,

Some of the error above in conan has been lost - **can you try to past more of the error?**

It looks like your system is failing to build boost as part of the conan install step, something inside b2...

If you can post a more complete log of the output I can try to work out whats going on for you.

Thanks,
- George

**Comment by OZTaekOppa** [comment]
Hi,

Here is the full list that I have tried.
Please see the attached file.

[Pod5_Issue.txt](https://github.com/nanoporetech/pod5-file-format/files/8810183/Pod5_Issue.txt)

I have activated the pip and cmake from bioconda environment. 

Cheers,

Taek

**Comment by jorj1988** [comment]
Hi @OZTaekOppa ,

The critical section of the log seems to be: ```
<compileflags>"-I/home/uqhjung3/.conan/data/libbacktrace/cci.20210118/_/_/package/3a5f72c8cd50641b8efa6ed13e6914c6ced2747c/include" <linkflags>"-L/home/uqhjung3/.conan/data/libbacktrace/cci.20210118/_/_/package/3a5f72c8cd50641b8efa6ed13e6914c6ced2747c/lib"  ;
boost/1.78.0: WARN: b2 -q target-os=linux architecture=x86 address-model=64 binary-format=elf abi=sysv --layout=system --user-config=/home/uqhjung3/.conan/data/boost/1.78.0/_/_/source/source_subfolder/tools/build/user-config.jam -sNO_ZLIB=0 -sNO_BZIP2=0 -sNO_LZMA=1 -sNO_ZSTD=1 boost.locale.icu=off --disable-icu boost.locale.iconv=on boost.locale.iconv.lib=libc threading=multi visibility=hidden link=static variant=release --with-atomic --with-chrono --with-container --with-context --with-contract --with-coroutine --with-date_time --with-exception --with-filesystem --with-iostreams --with-locale --with-log --with-program_options --with-random --with-regex --with-serialization --with-stacktrace --with-system --with-test --with-thread --with-timer --with-type_erasure --with-wave toolset=gcc define=_GLIBCXX_USE_CXX11_ABI=0 pch=on  cxxflags="-fPIC -DBOOST_STACKTRACE_ADDR2LINE_LOCATION=/usr/bin/addr2line" install --prefix=/home/uqhjung3/.conan/data/boost/1.78.0/_/_/package/cf5b1011055d170fc18a05ba048979d2089d1695 -j24 --abbreviate-paths -d0 --debug-configuration --build-dir="/home/uqhjung3/.conan/data/boost/1.78.0/_/_/build/cf5b1011055d170fc18a05ba048979d2089d1695"
b2: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by b2)
b2: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by b2)
boost/1.78.0:
boost/1.78.0: ERROR: Package 'cf5b1011055d170fc18a05ba048979d2089d1695' build failed
```

From the logs it looks like your compiler toolchain is quite old (GCC 4.8 was released ~2015) and the specific error at the end with b2 is related to libstdc++ not containing newer versions.

Can I ask what your platform/OS (and versions) are and if you have the most up to date compiler available?

If you have support for a package manager, you might want to try the instructions for building against OS packages here: https://github.com/nanoporetech/pod5-file-format#developing

If you can get me more info on your system, I can attempt to work on a solution - perhaps we can remove our boost dependency, if it is impossible to build on your platform.

Thanks,
George

**Comment by OZTaekOppa** [comment]
Hi George,

Thank you for your reply.
I will try again with a conda environment (using the latest GCC).

Regards,

Taek

**Comment by OZTaekOppa** [comment]
Unfortunately, there was no luck. Please see the attached file.

[Pod5_Issue2.txt](https://github.com/nanoporetech/pod5-file-format/files/8820736/Pod5_Issue2.txt)

And, my Univ. HPC is not allowed to use "sudo" command. 
Here is the link (https://rcc.uq.edu.au/flashlite).

Cheers,

**Comment by jorj1988** [comment]
Hi @OZTaekOppa ,

If you have a newer version of GCC on the box, you can invoke conan specifically with that compiler:

```
> conan install --build=missing -s build_type=Release -s compiler=gcc -s compiler.version=10 ..
```

That should cause conan to select the newer compiler - you may also need to set CC/CXX variables to get conan to select the right compilers.

Thanks,
- George

**Comment by jorj1988** [comment]
Hi @OZTaekOppa ,

The latest release 0.0.17 does not require a binary build of boost - so should resolve your issue, can you have another go and let us know?

- George

**Comment by OZTaekOppa** [comment]
Hi George,
Sorry for the late reply.
Now, it is working fine including the installation.
Thank you so much!
Taek

**Comment by asan-emirsaleh** [comment]
Hi all!
@OZTaekOppa  how did you fix the issue? Did you installed it inside conda environment? What packages also was bandled within it?
