### ISSUE TITLE
pod5 subset killed

### ISSUE THREAD

**Issue by SalvadorGJ** [nanoporetech/pod5-file-format#53]
Hi,

I tried to split a directory of POD5 files by channel, running pod5 `view` and `subset` as follows:
```
pod5 view pod5/ -t 8 -r -i "read_id,channel" --output flowCell_06_FLO-PRO114M.channels.txt
pod5 subset pod5/ -t 8 -r --table ./flowCell_06_FLO-PRO114M.channels.txt --columns channel --output flowCell_06_FLO-PRO114M.channel_subset
```

However I got the following error:
```
Parsed 85646760 targets
/scratch-cbe/users/salvador.gonzales/1_AmexGenomeAnnotation/1_AmexTranscriptomeAssembly/0_Dorado_Basecalling/9d/1b37ed9b79da3925da3ebccea1cf0c/.command.sh: line 6: 53789 Segmentation fault      pod5 subset pod5 -t 8 -r --table ./flowCell_06_FLO-PRO114M.channels.txt --columns channel --output flowCell_06_FLO-PRO114M.channel_subset
/usr/lib/python3.8/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 11 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
```

It's important to note that it seems that the first part of `subset` executes successfully, as indicated by the output `Parsed 85646760 targets`. Any suggestions about what is the problem and what could I try?

Python version is `Python 3.8.10`

Thanks in advance,
Salvador

**Comment by HalfPhoton** [comment]
Hi @SalvadorGJ ,

Thanks for reporting this issue.

After parsing the `view` table, subset will load all the metadata it needs into memory to create a mapping of source file to destination file for each read. Your system might be running out of memory when trying to do this for 85.6M reads into ~4k channel outputs. 

Could you please try the following:
* Reduce number of `--threads`
  *  This will lower the memory consumption by spawning fewer worker processes
* Process your workload in smaller batches
  * Group input pod5 files into more manageable batches of a few million reads  
  * Use the `-M/--missing-ok` flag if re-using the `view` output table as it will have more reads than in the batch of inputs

If this doesn't solve your issue please set the environment variable `POD5_DEBUG=1`  and send us the `.log` files that are generated so that we can further investigate this issue.
```
POD5_DEBUG=1 pod5 subset pod5/ -t 4 -r --table ./flowCell_06_FLO-PRO114M.channels.txt --columns channel --output flowCell_06_FLO-PRO114M.channel_subset
```

Kind regards,
Rich

**Comment by SalvadorGJ** [comment]
Hi Rich,

Thanks a lot for your suggestions. In the meantime I tried by upgrading `Python 3.10.6`, but got the same issue. Then I noticed your answer, and tried by reducing the number of threads.  Unfortunately the same problem persists, although seems that the process failure takes twice the time to appear. I executed:

```
pod5 view pod5/ -t 4 -r -i "read_id,channel" --output flowCell_06_FLO-PRO114M.channels.txt
POD5_DEBUG=1 pod5 subset pod5/ -t 4 -r --table ./flowCell_06_FLO-PRO114M.channels.txt --columns channel --output flowCell_06_FLO-PRO114M.channel_subset
```

```
Parsed 85646760 targets
/scratch-cbe/users/salvador.gonzales/1_AmexGenomeAnnotation/1_AmexTranscriptomeAssembly/0_Dorado_Basecalling/18/be725d286596cb196e7e0500a22a69/.command.sh: line 6: 31699 Segmentation fault      POD5_DEBUG=1 pod5 subset pod5/ -t 4 -r --table ./flowCell_06_FLO-PRO114M.channels.txt --columns channel --output flowCell_06_FLO-PRO114M.channel_subset
/usr/lib/python3.10/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 11 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
```

Here are the generated log files: 
[2023-06-28--12-17-01-p-33109-pod5.log](https://github.com/nanoporetech/pod5-file-format/files/11893130/2023-06-28--12-17-01-p-33109-pod5.log)
[2023-06-28--12-17-01-p-33110-pod5.log](https://github.com/nanoporetech/pod5-file-format/files/11893131/2023-06-28--12-17-01-p-33110-pod5.log)
[2023-06-28--12-17-01-p-33111-pod5.log](https://github.com/nanoporetech/pod5-file-format/files/11893132/2023-06-28--12-17-01-p-33111-pod5.log)
[2023-06-28--12-17-01-p-33108-pod5.log](https://github.com/nanoporetech/pod5-file-format/files/11893133/2023-06-28--12-17-01-p-33108-pod5.log)
[2023-06-28--12-14-38-main-pod5.log](https://github.com/nanoporetech/pod5-file-format/files/11893134/2023-06-28--12-14-38-main-pod5.log)

I will try the other alternatives you suggested. But I don't understand what do you mean with "Use the -M/--missing-ok flag if re-using the view output table as it will have more reads than in the batch of inputs". Could you please describe me what does the `--missing-ok` flag does, as its description (Allow missing read_ids) is not clear for me in the context I'm using.

I will keep in touch.

Kind regards,
Salvador

**Comment by HalfPhoton** [comment]
@SalvadorGJ 

Based on the log files you've supplied it looks like you're trying to subset about 21600 files at once, this is going to be quite taxing on resources. I would definitely recommend batch processing this task.

Kind regards, 
Rich

**Comment by SalvadorGJ** [comment]
Hi,

Thank you again for your help. Now I tried batching my file first and the `resource_tracker`  problem is solved. Unfortunately I found that the `subset` process is working very slowly. I'm sampling 21,572 files into batches of 5 files, which means 20,000 reads each batch, and each takes 30 min to finish using 4 cpus. As I will receive tons of more data in the following days, I was wondering if there is a way to speed the process. I'm already running jobs in parallel, but when I tried increasing the cpus to >8 some random issues appeared in different instances:

```
/scratch-cbe/users/salvador.gonzales/1_AmexGenomeAnnotation/1_AmexTranscriptomeAssembly/0_Dorado_Basecalling/5e/10efac02ab39c342b24f6a08fd93a8/.command.run: fork: retry: Resource temporarily unavailable
thread '<unnamed>' panicked at 'could not spawn threads: ThreadPoolBuildError { kind: IOError(Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }) }', /home/runner/work/polars/polars/polars/polars-core/src/lib.rs:61:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Process SpawnProcess-7:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/dist-packages/pod5/tools/utils.py", line 171, in wrapper
    ret = func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/pod5/tools/pod5_view.py", line 441, in worker_process
    for table in get_reads_tables(path, selection):
  File "/usr/local/lib/python3.10/dist-packages/pod5/tools/pod5_view.py", line 368, in get_reads_tables
    run_info = parse_run_info_table(reader)
  File "/usr/local/lib/python3.10/dist-packages/pod5/tools/utils.py", line 171, in wrapper
    ret = func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/pod5/tools/pod5_view.py", line 345, in parse_run_info_table
    run_info = pl.from_arrow(run_info_table, rechunk=False).lazy().unique()
  File "/usr/local/lib/python3.10/dist-packages/polars/convert.py", line 599, in from_arrow
    return pl.DataFrame._from_arrow(
  File "/usr/local/lib/python3.10/dist-packages/polars/dataframe/frame.py", line 612, in _from_arrow
    arrow_to_pydf(
  File "/usr/local/lib/python3.10/dist-packages/polars/utils/_construction.py", line 1323, in arrow_to_pydf
    pydf = PyDataFrame.from_arrow_record_batches(tbl.to_batches())
pyo3_runtime.PanicException: could not spawn threads: ThreadPoolBuildError { kind: IOError(Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }) }

POD5 has encountered an error: 'Unexpected exception ocurrecd in <SpawnProcess name='SpawnProcess-7' pid=76727 parent=75797 stopped exitcode=1 daemon> - exit code: 1'

For detailed information set POD5_DEBUG=1'
```

I found that decreasing the number of cpus avoids these kind of issues. But I'm curious if you have benchmarked that more cpus enhances considerably the running time for this specific tool. Any other suggestions are welcome.

Kind regards,
Salvador

**Comment by HalfPhoton** [comment]
Thanks for the update @SalvadorGJ I'm glad to hear that the main issue is resolved and you're able to make progress again. 

As for the performance question. There's a significant overhead while creating the thousands of (per-channel) output files. 

Batching in collections of 5 files might be unnecessarily small. Please try increasing your batch size while keeping the threads at a safe level. 
If there are 20k reads and 4k output files, there's only going to be about 5 reads per file which is not ideal. Hopefully 50/100/200 will remain stable and improve performance overall. `htop` or similar can give you a feel for how much scope you have for increasing the batch size.

Another option which is slightly more involved, would be to use the simpler `filter` tool and repeat the process per-channel. The filter tool doesn't need to perform the source to output mapping as there's only one output. This significantly reduces memory consumption and may give you better stability / performance. 

I hope this helps, kind regards,
Rich

**Comment by SalvadorGJ** [comment]
Hi Rich,

Thanks for your answer, I will try using filter. Before that I read the documentation and saw this warning: "When supplying multiple input files to ‘filter’ or ‘subset’, the tools is effectively performing a merge operation. The ‘merge’ tool is better suited for handling very large numbers of input files." 

So, that means I also need to use `merge` to a batch of files before running `filter`?

Best,
Salvador

**Comment by HalfPhoton** [comment]
That warning is probably a bit redundant now since the performance of the read search operation has improved significantly for many input files. You should be good to proceed as you are.

Kind regards,
Rich

**Comment by HalfPhoton** [comment]
@SalvadorGJ ,

Were you able to run `filter` with your dataset or increase the number of files in your batches?

Kind regards,
Rich

**Comment by SalvadorGJ** [comment]
Hi Rich,

I tried using `view` with all 21,573 raw pod5 files to generate the table of reads IDs and channels, that works fine and quick. Then I was trying to `subset` by batches of 2,000 files and use filter. I was able to run it, but it was a hard task for the workflow manager (Nextflow) to handle 29,392 jobs in parallel (11 batches * 2672 channels). However, we found later what seems the definite solution. We first use `merge` to concatenate batches of 100 raw files, so the input from the beginning of the pipeline will become just 216 big files. So, now we are able to run `filter` without needing to create batches because the tool is able to handle that amount of files at once, and the total of jobs is the same of the number of channels: 2672, which is cleaner for our pipeline. Thanks again for your help.

Kind regards,
Salvador

**Comment by HalfPhoton** [comment]
Thanks for getting back to us with an update @SalvadorGJ. 

I'll close this ticket as resolved but we will be looking into reducing memory consumption to improve stability and general performance improvements over the next few releases.

Kind regards,
Rich
