### ISSUE TITLE
No way to demultiplex pod5 files.

### ISSUE THREAD

**Issue by rjmat97** [nanoporetech/pod5-file-format#55]
Hi,

Is there any way to directly demultiplex pod5 files like how you can with fast5 files? 

Im currently converting pod5 > fast5 and then then back to pod5 after demultiplexing fast5.

Thankyou

**Comment by Psy-Fer** [comment]
Hey, have you looked at pod5 subset?

Search for it here. 

https://github.com/nanoporetech/pod5-file-format/blob/master/python/pod5/README.md

That should do what you are looking for.

**Comment by HalfPhoton** [comment]
There's also documentation on [ReadTheDocs](https://pod5-file-format.readthedocs.io/en/latest/docs/tools.html#pod5-subset)

Do you need further support with this issue?

**Comment by rjmat97** [comment]
Thankyou
