### ISSUE TITLE
'No progress in 600 seconds - quitting'

### ISSUE THREAD

**Issue by lucky5sugar** [nanoporetech/pod5-file-format#58]
Hi
I would like to convert over 10,000 fast5 files into pod5 files but program stops with this error message.
```
CRITICAL:pod5:Empty queue or timeout 
An unexpected error occurred: No progress in 600 seconds - quitting 
```
Before reaching this error, there are two other errors popping up like this:
```
ERROR:pod5:Input PAK65494_pass_cb49d460_6ca8a6a6_8397.fast5 is not a multi-read fast5

*** Error in `/home/my/miniconda3_centos7/envs/pod5/bin/python': munmap_chunk(): invalid pointer: 0x000000000e9771e0 ***
```

I am using this code to convert fast5 files.
`pod5 convert fast5 path/to/*.fast5 --output ./ -t 20 --one-to-one path/to/` 

I downloaded this program using pip on a conda environment.
Converting one fast5 file does not cause any errors.

**Comment by HalfPhoton** [comment]
Hi @lucky5sugar , 

Which pod5 version are you using?

It looks like you have a bad fast5 file can you remove it and try again?

Kind regards,
Rich

**Comment by HalfPhoton** [comment]
@lucky5sugar ,

Are there any updates on this issue?

Kind regards,
Rich

**Comment by lucky5sugar** [comment]
@HalfPhoton ,
Thank you for your replies. Pod5 version is 0.2.3.

I could not open those bad fast5 files with other programs (HDFview & Guppy).
Is there any method to detect and remove those bad fast5 files?
Alternatively, can pod5 ignore those files and continue the analysis?

**Comment by HalfPhoton** [comment]
The converter should be able to handle bad inputs. 
You're seeing the `Error:` message from the error handler, but it appears that this error in `h5py` is causing the child python interpreter to be enter a bad state following `munmap_chunk(): invalid pointer`. This makes the parent process quit (timeout) as it gets no response from the child process. 

We used to pre-check the files but this was taking a very long time for large numbers of inputs and so it was removed.  We'll look into improving the bad input handler.

Here's a solution to check your `fast5s` manually:

```python
from pathlib import Path
from pod5.tools.pod5_convert_from_fast5 import is_multi_read_fast5

# Your path here or leave as current working directory
input_dir = Path.cwd()

# Optionally search recursively
recursive = True
glob = Path.rglob if recursive else Path.glob

for fast5 in glob(input_dir, "*.fast5"):
    relative = fast5.relative_to(input_dir)
    if is_multi_read_fast5(fast5):
        print(f"error: {relative}")
    else: 
        print(f"ok: {relative}")
```

**Comment by lucky5sugar** [comment]
@HalfPhoton , 
Thank you for the python command.
As I ran that command, the same error that popped up with pod5-convert emerged (I attached the error message in the txt file below).
Could you teach how to deal with the problem?

[multi_read_fast5_inspector_error.txt](https://github.com/nanoporetech/pod5-file-format/files/12092719/multi_read_fast5_inspector_error.txt)

**Comment by HalfPhoton** [comment]
@lucky5sugar ,

We need to identify the corrupt files and remove them from your set. Because it's crashing python we'll need to test each file in a child python process. 

Please run this `tester` script. It will output a list of bad fast5 files as well as show progress as you have so many input files.
```bash
python -m tester > bad_fast5s.txt
testing: 100%|██████████████████████████████| 989/989 [00:00<00:00, 2238.13it/s]
```

With the list of bad fast5s you can then move them out of your dataset and continue with your conversion.

`tester.py` :
```python
import os
from pathlib import Path
from concurrent.futures import ProcessPoolExecutor, as_completed
import sys
from tqdm.auto import tqdm

from pod5.tools.pod5_convert_from_fast5 import is_multi_read_fast5

# Number of workers
NUM_WORKERS=os.cpu_count()

# Your path here or leave as current working directory
input_dir = Path.cwd()

# Optionally search recursively
recursive = True
glob = Path.rglob if recursive else Path.glob

with ProcessPoolExecutor(max_workers=NUM_WORKERS) as executor:
    
    # Launch a tester sub-process for each file
    futures = {}
    for fast5 in glob(input_dir, "*.fast5"):
        future = executor.submit(is_multi_read_fast5, fast5)
        futures[future] = fast5
    
    pbar = tqdm(total = len(futures), desc="testing", file=sys.stderr)
    with pbar:
        for future in as_completed(futures):
            fast5 = futures[future]
            
            # Check if there was an exception raised by the sub-process or if the
            # test showed that it was not a fast5 file
            if future.exception() or not future.result():
                pbar.write(f"{fast5.absolute()}", file=sys.stdout)
            pbar.update()
   
```

**Comment by lucky5sugar** [comment]
@HalfPhoton 
Thank you for providing me with a solution program. 
Unfortunately, `tester.py` outputted the file names of normal fast5 and then halted with the same error message as before. I think it encountered an abnormal fast5 file.

When I tried to open these abnormal fast5 files using the h5ls command, I received error messages, and I was able to remove these files. After doing so, pod5 ran perfectly with the normal fast5 files, of which there were over 10,000. 

The issue was that the pod5 program did not have a handler for bad input, so we had to manually remove those corrupted fast5 files.
Thank you so much!

**Comment by billytcl** [comment]
I am getting this error too, but with no obvious problem before the error. Any ideas?

```
(base) [billylau@sh03-ln06 login /scratch/groups/hanleeji/20221104_PRM_1295]$ tail slurm-30684690.out
Converting 30037 Fast5s: 100%|#########9| 118874961/118888161 [3:51:21<00:01, 8563.80Reads/s]CRITICAL:pod5:Empty queue or timeout 
An unexpected error occurred: No progress in 600 seconds - quitting                          
Converting 30037 Fast5s: 100%|#########9| 118874961/118888161 [4:01:09<00:01, 8215.40Reads/s]
POD5 has encountered an error: 'No progress in 600 seconds - quitting'

For detailed information set POD5_DEBUG=1'
Converting 30037 Fast5s: 100%|#########9| 118874961/118888161 [4:01:35<00:01, 8200.58Reads/s]
```

**Comment by jorj1988** [comment]
Hi @billytcl ,

Can you confirm what version of python + pod5 you're using, and the original command that causes the issue?

Thanks,
- George

**Comment by billytcl** [comment]
The command is pod5 convert fast5 -o pod5/converted.pod5 -r -t 20
./Seq_Output/

Interestingly this doesn't happen to all runs. I can't tell if it's a
corrupt fast5 file or if there was an IO stall on the HPC.

Here are package versions:

(/home/groups/hanleeji/pod5_env) ***@***.*** ~] (job 30790618) $
conda list
# packages in environment at /home/groups/hanleeji/pod5_env:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
ca-certificates           2023.5.7             hbcca054_0    conda-forge
h5py                      3.8.0                    pypi_0    pypi
importlib-metadata        6.6.0                    pypi_0    pypi
iso8601                   2.0.0                    pypi_0    pypi
ld_impl_linux-64          2.40                 h41732ed_0    conda-forge
lib-pod5                  0.2.4                    pypi_0    pypi
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 13.1.0               he5830b7_0    conda-forge
libgomp                   13.1.0               he5830b7_0    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libsqlite                 3.42.0               h2797004_0    conda-forge
libstdcxx-ng              13.1.0               hfd8a6a1_0    conda-forge
libzlib                   1.2.13               h166bdaf_4    conda-forge
more-itertools            9.1.0                    pypi_0    pypi
ncurses                   6.4                  hcb278e6_0    conda-forge
numpy                     1.21.6                   pypi_0    pypi
openssl                   3.1.1                hd590300_1    conda-forge
packaging                 23.1                     pypi_0    pypi
pip                       23.1.2             pyhd8ed1ab_0    conda-forge
pod5                      0.2.4                    pypi_0    pypi
polars                    0.17.15                  pypi_0    pypi
pyarrow                   11.0.0                   pypi_0    pypi
python                    3.7.12          hf930737_100_cpython
 conda-forge
pytz                      2023.3                   pypi_0    pypi
readline                  8.2                  h8228510_1    conda-forge
setuptools                67.7.2             pyhd8ed1ab_0    conda-forge
sqlite                    3.42.0               h2c6b66d_0    conda-forge
tk                        8.6.12               h27826a3_0    conda-forge
tqdm                      4.65.0                   pypi_0    pypi
typing-extensions         4.6.3                    pypi_0    pypi
vbz-h5py-plugin           1.0.1                    pypi_0    pypi
wheel                     0.40.0             pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
zipp                      3.15.0                   pypi_0    pypi

**Comment by HalfPhoton** [comment]
Hi @billytcl , can you please run with the `POD5_DEBUG=1` set and set us the log files generated? This will tell us where the issue is. 

Kind regards,
Rich

**Comment by billytcl** [comment]
Here are the log files! This file expires in 48 hours.

https://www.dropbox.com/scl/fi/c80gb0mdojz7y3s1gkcw9/pod5_convert.log.tar.gz?rlkey=72pgxaiqwnunfyq9t5z4brzkl&dl=0
