### ISSUE TITLE
end_reason changelog or docs

### ISSUE THREAD

**Issue by Psy-Fer** [nanoporetech/pod5-file-format#61]
Hey

I'm wondering if there are any docs on the use/state of `end_reason`?

Something that, for example, allows us to guess the `end_reason` enum based on the MinKNOW version?

Also, how does pod5 handle this? i can see a hard-coded enum class for the following fields

```class EndReasonEnum(enum.Enum):
    """EndReason Enumeration"""

        UNKNOWN = 0
        MUX_CHANGE = 1
        UNBLOCK_MUX_CHANGE = 2
        DATA_SERVICE_UNBLOCK_MUX_CHANGE = 3
        SIGNAL_POSITIVE = 4
        SIGNAL_NEGATIVE = 5


        _END_REASON_FORCED_DEFAULTS: Dict[EndReasonEnum, bool] = {
            EndReasonEnum.UNKNOWN: False,
            EndReasonEnum.MUX_CHANGE: True,
            EndReasonEnum.UNBLOCK_MUX_CHANGE: True,
            EndReasonEnum.DATA_SERVICE_UNBLOCK_MUX_CHANGE: True,
            EndReasonEnum.SIGNAL_POSITIVE: False,
            EndReasonEnum.SIGNAL_NEGATIVE: False,
        }
```

but before, the fields were

```
slow5_end_reason_labels = ['unknown', 
                           'partial',
                           'mux_change',
                           'unblock_mux_change',
                           'signal_positive',
                           'signal_negative']
```

So what happened to `partial` and what is `DATA_SERVICE_UNBLOCK_MUX_CHANGE` ?

What is `end_reason_forced` and while there are `_END_REASON_FORCED_DEFAULTS`, what are the conditioned when this would change, and what is it used for?

What is the strategy for naming/ordering these in the future?

This field has always been a bit of a problem area for us when doing conversions, or even trying to understand what it's used for, so if there are any docs about its use I would love to read them.

Anyway, the reason i'm asking is because i'm cleaning up our `blue-crab` repo for POD5<->SLOW5 conversion and I need to know the specifics so I can handle things as they change.

Cheers,
James

**Comment by jorj1988** [comment]
Hi @Psy-Fer ,

I can't comment on the contents of the slow5 enum - but the options minknow has written to fast5 for some time are: 

```
        Unknown,
        Partial,
        MuxChange,
        UnblockMuxChange,
        DataServiceUnblockMuxChange,
        SignalPositive,
        SignalNegative,
```

In terms of how pod5 uses this - as you say its treated as a hardcoded enum. MinKNOW decides how a read ended when acquisition is running and writes one of the hardcoded labels to the output file format.

`Partial` is an end reason that implies the read is still in progress internally, and should not ever be written to a final file. Its an internal artifact of how our fast5 writer is implemented that it was available in the enum set. We fixed this for Pod5.

`DataServiceUnblockMuxChange` has been present for some time, it is the end reason used when a read is terminated using the adaptive sampling API's.

`end_reason_forced` is a field intended to help users who don't want to know about the enum, and instead want to query if a read ended naturally. See docs here for more: https://github.com/nanoporetech/pod5-file-format/blob/master/docs/tables/reads.toml#L75. `end_reason_forced` can be derived from the enum value, if you know all possible enum values. If you don't want to encode knowledge of minknow/pod5 enums in your program, or happen to read a file with a new end reason in, `end_reason_forced` is a field which you can still understand and use in your program.

`_END_REASON_FORCED_DEFAULTS` is detail used by the pod5 tools to find a default value for the `end_reason_forced` field from a given end reason.

> What is the strategy for naming/ordering these in the future?

We don't have current plans to add new reasons, if we do we would not reuse integer values, so would plan to add to the end. I can't comment on naming as I have no plans currently to add more.

> This field has always been a bit of a problem area for us when doing conversions, or even trying to understand what it's used for, so if there are any docs about its use I would love to read them.

There were docs for the field in release notes when first added to minknow output formats... I don't have a link to these right now, but potentially the nanopore community will?

Hope this helps,

Thanks,
- George

**Comment by Psy-Fer** [comment]
Hey George,

Thanks for the info. That is really helpful.

I will note that `DataServiceUnblockMuxChange` was added to the middle, and `partial` disappeared, which is why I was concerned about ordering in the enum. But if it's true that it's somewhat stable now, and adding to the end is the plan (even just you saying that it's the plan) is good enough for me I guess.

My current conversion looks something like this

```python
def s2p_end_reason_convert(end_reason):
    '''
    take an end_reason from slow5, and convert it to the current pod5 format and it's forced default
    mapping "partial" to UNKNOWN
    '''
    pod5_end_dic = {
        "unknown": (p5.EndReasonEnum.UNKNOWN, False),
        "partial": (p5.EndReasonEnum.UNKNOWN, False),
        "mux_change": (p5.EndReasonEnum.MUX_CHANGE, True),
        "unblock_mux_change": (p5.EndReasonEnum.UNBLOCK_MUX_CHANGE, True),
        "data_service_unblock_mux_change": (p5.EndReasonEnum.DATA_SERVICE_UNBLOCK_MUX_CHANGE, True),
        "signal_positive": (p5.EndReasonEnum.SIGNAL_POSITIVE, False),
        "signal_negative": (p5.EndReasonEnum.SIGNAL_NEGATIVE, False),
    }

    try:
        ret = pod5_end_dic[end_reason]
    except:
        print("s2p_end_reason_convert: end_reason - {} - not found, please contact developers".format(end_reason))
        sys.exit(1)
    return ret[0], ret[1]
```

Here I map partial to UNKNOWN. Do you think that is valid? what do you guys do for fast5->pod5 conversions for this no longer-used field?

**Comment by HalfPhoton** [comment]
@Psy-Fer ,

This is the same as what we do in the fast5 converter [convert_fast5_end_reason](https://github.com/nanoporetech/pod5-file-format/blob/master/python/pod5/src/pod5/tools/pod5_convert_from_fast5.py#L401). 

Kind regards,
Rich

**Comment by Psy-Fer** [comment]
Ahh perfect. Thanks rich.

Some of the code there helps with the time conversions too, I'll borrow that.

That clears things up for this particular set of questions.

Thanks guys, appreciate the help and info!

James
