### ISSUE TITLE
Q: --recursive only for POD5 input?

### ISSUE THREAD

**Issue by sklages** [nanoporetech/pod5-file-format#65]
Just a quick question: `--recursive` works on POD5 data, e.g. when merging a bunch of pod5 files (merge). 
This parameter does **not** work with `fast5->pod5` conversion (convert, reading fast5 data recursively).
Is that correct? At least it ignores fast5 files in subdirectories here (Pod5 version: 0.2.4)

**Comment by jorj1988** [comment]
It _should_ work with recursive fast5 files - I've checked the source and tested locally, and it worked as expected in small scale tests.

Can you provide the command you are running? Can you also provide some kind of snapshot of your directory layout?

Thanks,
- George

**Comment by sklages** [comment]
@jorj1988 - Well, the test case is a directory with symbolic links to fast5 directories of a prom run:
```
$ ls -l /path/to/fclinks
lrwxrwxrwx 1 xxxx yyyy 2023-08-30 19:02:10  17 B  PAE86216 ⇒ ../fast5/PAE86216
lrwxrwxrwx 1 xxxx yyyy 2023-08-30 19:02:10  17 B  PAE91419 ⇒ ../fast5/PAE91419
```

These directories contain links to fast5 files on some NFS mount, like
```
$ tree -l
.
|-- PAE86216 -> ../fast5/PAE86216
|   |-- PAE86216_e071640c_0.fast5   -> /path/to//PAE86216_e071640c_0.fast5
|   |-- PAE86216_e071640c_100.fast5 -> /path/to//PAE86216_e071640c_100.fast5
|   |-- PAE86216_e071640c_101.fast5 -> /path/to//PAE86216_e071640c_101.fast5
<...>
```

Running pod5:
```
$ cd /path/to/fclinks

$ pod5 convert fast5 --force-overwrite --strict --recursive --output new.pod5 $(pwd)
CRITICAL:pod5:Found no *.fast5 files in inputs: [PosixPath('/path/to/sk.f5')]

POD5 has encountered an error: 'Found no fast5 inputs to process - Exiting'
For detailed information set POD5_DEBUG=1'
```

Creating a directory in `/path/to/fclinks`, copying some fast5 files and then run the same command works just fine.

So I think, `pod5` does not follow symbolic links on Linux.

**Comment by jorj1988** [comment]
Hi @sklages,

Good catch, we are working on a solution to this internally now.

Thanks,
- George

**Comment by jorj1988** [comment]
Hi @sklages,

0.3.0 is now live and will follow symlinks.

Hope that helps,
- George
