### ISSUE TITLE
how much information you loose when you convert fast5 to pod5 and back to fast5?

### ISSUE THREAD

**Issue by sahuno** [nanoporetech/pod5-file-format#67]
Que 1- would there be any time we'll regret deleting the original fast5 files after converting to pod5 file format?
Que 2 - do you loose information if you convert pod5 files back to fast5? and by how much?

for context we have fast5 files which i converted to pod5 to run basecalling with `dorado`, the ONT base calling software. 
we want to decide whether to delete the fast5 files we just converted to pod5 so want to make an information choice. 

thanks in advance for your help!

**Comment by jorj1988** [comment]
Hi @sahuno,

The pod5 files hold the complete raw data from the sequencing device, and all tracking information and experiment metadata held in the fast5.

On conversion back to fast5 the raw signal is again stored 1:1 (recompressed losslessly). The basecalls you get by passing fast5 or pod5 will be equivalent.

I hope that helps,
- George

**Comment by sahuno** [comment]
this very useful information @jorj1988
thanks for taking the time to explain.
closing....
