### ISSUE TITLE
is there option for threading?

### ISSUE THREAD

**Issue by sahuno** [nanoporetech/pod5-file-format#69]
Dear Developers, 
is there option to allowing threading of `pod5 convert` . & how can i utilize it?
maybe i missed this

thanks
-S

**Comment by Psy-Fer** [comment]
Hey,

The -t or --threads will give you control over the number of threads to use for that sub module.

James

**Comment by sahuno** [comment]
thanks @Psy-Fer for the clarification! 
duplicate post dues to internet connection issues. 
So moving to close this one.
