### ISSUE TITLE
pod5 to fast5?

### ISSUE THREAD

**Issue by RichardCorbett** [nanoporetech/pod5-file-format#7]
Hi folks,

I was able to convert a folder of fast5s to pod5 without any issues.   Is there a tool for reversing the process?

**Comment by jorj1988** [comment]
Hi @RichardCorbett,

We don't have a tool for this yet - but we intend to build one at some point - but haven't shipped it yet.

Thanks,
- George

**Comment by Psy-Fer** [comment]
If you happened to delete the fast5 data after conversion to pod5, and you need to go back to fast5, you can use this:

https://github.com/Psy-Fer/project_blue_crab

This will let you go pod5->slow5
Then you can go slow5->fast5 with slow5tools

You will lose the end_reason value though (not really used for anything yet), as well as the digitisation and range, though we use a trick that makes that not matter with tools that use those fields. This is not ideal, but it's all we can do with the current state of pod5.

This can be used as a stop-gap solution until ONT get around to making their converter go both ways.

**Comment by jorj1988** [comment]
Hi @RichardCorbett ,

The latest release 0.0.17 has preliminary support for converting files back to fast5. Please have a go and let us know your feedback!

- George
