### ISSUE TITLE
is there option for threading for pod5 convert?

### ISSUE THREAD

**Issue by sahuno** [nanoporetech/pod5-file-format#70]
Dear Developers, 
is there option to allowing threading of `pod5 convert` . & how can i utilize it?
maybe i missed this

thanks
-S

**Comment by sklages** [comment]
`pod5 convert fast5 --help`

.. `-t THREADS, --threads THREADS` :  Set the number of threads to use (default: 4)

**Comment by sahuno** [comment]
@sklages i think i missed that with `pod5 convert from_fast5 --help`
Que: what's difference between `pod5 convert fast5` and `pod5 from_fast5` ? 
i installed pod5 with `pip install pod5`

**Comment by sklages** [comment]
> @sklages Que: what's difference between `pod5 convert fast5` and `pod5 from_fast5` ?

`from_pod5` is just an alias to `fast5`
