### ISSUE TITLE
'Argument list too long' for 'pod5 convert fast5' command

### ISSUE THREAD

**Issue by Flower9618** [nanoporetech/pod5-file-format#71]
Hi, when I run `pod5 convert fast5`, there is an error: argument list too long. 
I need to convert more than 10k fast5 files each with 4000 reads into pod5 file to run dorado.

**Comment by sklages** [comment]
How did you run `pod5`? How did your exact command look like?

**Comment by Flower9618** [comment]
Hi, @sklages . The command is like:

`pod5 convert fast5 data/*.fast5 --output ./ --one-to-one data/ -t 50`

**Comment by sklages** [comment]
The error may be raised by your shell because `data/*.fast5` gets expanded before `pod5` is started. You can either increase your shell limits or better try to run your conversion by simply providing the data directory as input: 
(I have added an output folder name)
```bash
pod5 convert fast5 data/ --output ./data_pod5 --one-to-one data -t 50
```

**Comment by Flower9618** [comment]
Hi, @sklages . Thank you so much for your help. It is very helpful for me.
