### ISSUE TITLE
pod5 subset incorrect usage line

### ISSUE THREAD

**Issue by cfblaeb** [nanoporetech/pod5-file-format#74]
The pod5 subset usage line (and probably all the other tools as well) is wrong.
It says:
pod5 subset [-h] [-o OUTPUT] [-r] [-f] [-t THREADS] [--csv CSV] [-s TABLE] [-R READ_ID_COLUMN] [-c COLUMNS [COLUMNS ...]] [--template TEMPLATE] [-T] [-M] [-D] inputs [inputs ...]

but "inputs" actually needs to be the first parameter

**Comment by HalfPhoton** [comment]
Hi @cfblaeb , do you have an example which demonstrates this?

This usage information is automatically generated from the python argparse module and we've not experienced this issue to the best of my knowledge.

Kind regards,
Rich

**Comment by HalfPhoton** [comment]
Hi @cfblaeb,

I believe this is a limitation of the python argparse module. The `--columns` parameter can take multiple inputs and is greedily consuming your positional `inputs` argument incorrectly. 

This variant of your command will work as the `--summary` parameter consumes only one argument.

```bash
pod5 subset -o barcoded_pod5 -t 32 -c barcode_arrangement -s barcoded/barcoding_summary.txt pod5_folder

```

Thanks for bringing this to our attention though. We'll look at making this clear in the `--help` or documentation

**Comment by Psy-Fer** [comment]
One option is to modify pod5 to use `action="append"` instead of `nargs="+"`. This would mean the user would do something like
```
pod5 subset -o barcoded_pod5 -t 32 -s barcoded/barcoding_summary.txt -c barcode_arrangement1 -c barcode_arrangement2 pod5_folder
```

This means it won't consume the positional, and is only a very minor change in the usage

I hope that helps :)

**Comment by HalfPhoton** [comment]
Thanks for the suggestion @Psy-Fer , we'll look into updating this.
