### ISSUE TITLE
input file 'is not a multi-read fast5'

### ISSUE THREAD

**Issue by yanchunzhang** [nanoporetech/pod5-file-format#75]
I'm tring to convert fast5 to pod5. But got error saying 'is not a multi-read fast5'. Does it mean pod5 convert cannot work with single-read fast5 file?

Thanks,
Yanchun

**Comment by HalfPhoton** [comment]
Hi @yanchunzhang , yes, the conversion tool [expects multi-read fast5s](https://pod5-file-format.readthedocs.io/en/latest/docs/tools.html#pod5-convert-fast5).

You can convert them to multi-read fast5s with [ont_fast5_api](https://pypi.org/project/ont-fast5-api/)
