### ISSUE TITLE
Signal and record compression methods

### ISSUE THREAD

**Issue by hiruna72** [nanoporetech/pod5-file-format#76]
Hello,

Can we use pod5tools to get information of the compression methods used in a pod5 file?

Thank you.

**Comment by jorj1988** [comment]
Hi @hiruna72 ,

Please see the `signal_tools` section of the api: https://pod5-file-format.readthedocs.io/en/latest/reference/api/pod5.signal_tools.html

https://github.com/nanoporetech/pod5-file-format/blob/master/python/pod5/src/pod5/signal_tools.py

Thanks,
- George

**Comment by Psy-Fer** [comment]
So it's always vbz?

Could it ever be something else, and if so, would that information be stored anywhere in the metadata?

Cheers,

**Comment by jorj1988** [comment]
The columns are typed in arrow, if there was another method added, the type of the column would reflect that - see:

https://github.com/nanoporetech/pod5-file-format/blob/master/docs/tables/signal.toml#L6

Sorry, maybe I misunderstood the question, was the desire to compress some data using the same method as pod5 would but external to the file format, or do you want to query what method of compression is used?

Thanks,
- George

**Comment by jorj1988** [comment]
Ah, right.

Yes, you can get the schema and query directly using `reader.signal_table.schema`, or this method: https://github.com/nanoporetech/pod5-file-format/blob/master/python/pod5/src/pod5/reader.py#L790

Exists to confirm if the file is vbz compressed.

Thanks,
- George

**Comment by Psy-Fer** [comment]
Nice.

Is it presented in any of the output from the cmd line tools? Or just from the api?

**Comment by jorj1988** [comment]
Just checking through I don't think it is - it would be simple to add to the `inspect` command though.

We can look to add that in an upcoming release.

Thanks,
- George

**Comment by Psy-Fer** [comment]
Great!

Cheers George

**Comment by hiruna72** [comment]
Thanks @jorj1988 and @Psy-Fer.
Looking forward to using the new version.
