### ISSUE TITLE
Get the set of raw signal files from a pod5 dataset given a list of read ids.

### ISSUE THREAD

**Issue by hiruna72** [nanoporetech/pod5-file-format#77]
Hello,

Could you please give an abstract idea on how to write a CPP code to get the set of raw signals given a read id list (random access)?
I wrote something similar to what is found in [dorado](https://github.com/nanoporetech/dorado/blob/b2e54b8bb6348dc418b45722b96fe001a36a0497/dorado/data_loader/DataLoader.cpp#L194).
This works well when there's only a single pod5 file.
But how can I achieve the same when I have many pod5 files inside the directory?

Thank you very much!

**Comment by jorj1988** [comment]
Hi @hiruna72 ,

This example: https://github.com/nanoporetech/pod5-file-format/blob/master/c%2B%2B/examples/find_specific_read_ids_with_signal.cpp

Should help you out, I think it does exactly what you need using the C API.

Thanks,
- George

**Comment by hiruna72** [comment]
Hello @jorj1988,

Thanks for the example. However this is what I have already.
Let's say I have two pod5 files in a directory with each having two reads. 
P0 - [r0, r1]
P1 - [r2, r3]

Now my read list file has all four reads (r0, r1, r2, r3).
How do I query the pod5 directory (the dataset)?
Is it as trivial as running the code you shared for each pod5 file (adding a for loop to iterate over the files inside the dir)? Or is there a better way to do it?

Thank you.

**Comment by jorj1988** [comment]
Hi @hiruna72,

Yes, you can use the code provided to search for reads, and allow only _some_ of them to be found, knowing the rest are in the next file(s).

Hope that helps,
- George

**Comment by hiruna72** [comment]
Thank you for the information!
