### ISSUE TITLE
Is fast5 converted form pod5 different from the fast5 saved by the sequencer?

### ISSUE THREAD

**Issue by onkar2470** [nanoporetech/pod5-file-format#81]
Hi,
I am trying to run tombo resquiggle on  the fast5s converted from the pod5 files and I am getting error "AttributeError: 'str' object has no attribute 'decode'" with 100% reads unsuccessfully processed.
But when I am running tombo resquiggle on  the fast5s that are directly saved by the sequencer in fast5 format and not in pod5 format, in this case the resquiggle command is working fine.

That makes me curious if the fast5s converted from pod5s are having some difference which is incompatible with the tombo commands.

I am attaching the screenshot for the full error that I am getting.

![image](https://github.com/nanoporetech/pod5-file-format/assets/58908530/ce9bbdc3-6e6d-42d0-a997-cb975bb6a93f)

**Comment by HalfPhoton** [comment]
Hi @onkar2470 , apologies for the delayed reply.

This issue should be resolved with the release of 0.3.0 from a few weeks ago.

Kind regards,
Rich
