### ISSUE TITLE
[errno 30] Read-only file system

### ISSUE THREAD

**Issue by zalibke** [nanoporetech/pod5-file-format#83]
I'm trying to convert R9.4.1 fast5s to pod5 with the following command (M1 mac)

pod5 convert fast5 *.fast5 --output /output

An unexpected error occurred: IOError: Failed to open local file '//.43c24735-8063-42ff-b9bf-50abd77e109f.tmp-reads'. Detail:      [errno 30] Read-only file system
Converting 72 Fast5s:   0%|                               | 0/288000 [00:01<?, ?Reads/s]
POD5 has encountered an error: 'IOError: Failed to open local file '//.43c24735-8063-42ff-b9bf-50abd77e109f.tmp-reads'. Detail: [errno 30] Read-only file system'

For detailed information set POD5_DEBUG=1'
Converting 72 Fast5s:   0%|                               | 0/288000 [00:01<?, ?Reads/s]

Seems to be a permissions error on an internal temp file. Any ideas for troubleshooting? how can I go about setting POD5_DEBUG=1?

**Comment by jorj1988** [comment]
Hi @zalibke,

From the command it looks like you dont have permission to write to the `/` directory, but your command asks pod5 to take all fast5 files in the current dir and write all the reads into a new pod5 file `output` in the `/` directory.

It depends what you wanted to do:

*Write one file for each fast5 file* - see the `--one-to-one` option for the `convert` command.

*Output into the `/output` dir* - provide a full path for the output file to a writable location

From the docs for the convert command:
```
  -o OUTPUT, --output OUTPUT
                        Output path for the pod5 file(s). This can be an existing directory (creating 'output.pod5' within it) or a new named file path. A directory must be given when using --one-to-one. (default: None)
```

I hope that helps?

Thanks,
- George
