### ISSUE TITLE
Fast5 to pod5 failure

### ISSUE THREAD

**Issue by pilaralv** [nanoporetech/pod5-file-format#84]
Hi all,

I am getting this error when trying to convert some fast5s to pod5s:
`FATAL:  while initializing starter command: while copying engine configuration: engine configuration too big > 1048448
`
This is our conversion command (we have successfully used this for other samples):
`pod5 convert fast5 ${PATH_TO_FLOWCELL}/fast5/*.fast5 -r --output ${OUT_PATH}/pod5_${SAMPLE} --one-to-one ${PATH_TO_FLOWCELL}/fast5`

Has anyone seen this before?

Thanks!

**Comment by HalfPhoton** [comment]
Hi @pilaralv ,

You may have a very large number of fast5 files being collected by the wildcard `*.fast5`. There is some limit to how many characters can be passed to a command after expansion and this maybe what you're observing.

Please pass the directory as the input, without the glob.

```pod5 convert fast5 ${PATH_TO_FLOWCELL}/fast5/  `

Please note that the convert tool does not currently follow symlinks.

This is a change that will be coming soon though.
