### ISSUE TITLE
ModuleNotFoundError: No module named '_version'

### ISSUE THREAD

**Issue by npavlovikj** [nanoporetech/pod5-file-format#85]
Hi,

I am trying to install `lib_pod5` from scratch following the instructions here, https://pod5-file-format.readthedocs.io/en/latest/docs/install.html#installation-from-source.

However, when I run `python -m pod5_make_version`, I get the following error message, `ModuleNotFoundError: No module named '_version'`, e.g.,:
```
(pod5) [fedora@npavlovikj-vm pod5-file-format]$ python -m pod5_make_version
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/fedora/pod5/pod5-file-format/pod5_make_version.py", line 7, in <module>
    from _version import __version__, __version_tuple__
ModuleNotFoundError: No module named '_version'
```

If I skip this step, and proceed with `cmake -DENABLE_CONAN=ON -DCMAKE_BUILD_TYPE=Release ..`, I am getting the following error:
```
CMake Error at CMakeLists.txt:5 (include):
  include could not find requested file:
    /home/fedora/pod5/pod5-file-format/cmake/POD5Version.cmake
```

If I comment out the line `include(${PROJECT_SOURCE_DIR}/cmake/POD5Version.cmake)` in `CMakeLists.txt`, the version variables in `/home/fedora/pod5/pod5-file-format/build/c++/pod5_format/version.h` are empty, and I am getting:
```
/home/fedora/pod5/pod5-file-format/build/c++/pod5_format/version.h:8:40: error: expected primary-expression before ';' token
    8 | std::uint16_t const Pod5MinorVersion = ;
      |                                        ^
/home/fedora/pod5/pod5-file-format/build/c++/pod5_format/version.h:9:38: error: expected primary-expression before ';' token
    9 | std::uint16_t const Pod5RevVersion = ;
```
errors when running `make`.

I tried with both the newest version on GitHub and the released tarball, and I encountered the same error with both.

Is it possible that some files are missing from the `pod5` distribution?
If not, what workaround I can use so I can successfully compile `lib_pod5` from source?

Please let me know if you need any additional information.

Thank you,
Natasha

**Comment by jorj1988** [comment]
Hi @npavlovikj ,

What was the output of the `python -m setuptools_scm` command you ran?

Thanks,
- George

**Comment by npavlovikj** [comment]
Hi @jorj1988 ,

Thank you for your reply!

`python -m setuptools_scm` returns `0.2.4`:
```
(pod5) [fedora@npavlovikj-dev pod5]$ git clone https://github.com/nanoporetech/pod5-file-format.git
(pod5) [fedora@npavlovikj-dev pod5]$ cd pod5-file-format/
(pod5) [fedora@npavlovikj-dev pod5-file-format]$ git submodule update --init --recursive
(pod5) [fedora@npavlovikj-dev pod5-file-format]$ python -m setuptools_scm
0.2.4
(pod5) [fedora@npavlovikj-dev pod5-file-format]$ ls cmake/
BuildFlatBuffers.cmake  FindArrow.cmake  Findzstd.cmake  pod5_packaging.cmake
(pod5) [fedora@npavlovikj-dev pod5-file-format]$ python -m pod5_make_version
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/fedora/pod5/pod5-file-format/pod5_make_version.py", line 7, in <module>
    from _version import __version__, __version_tuple__
ModuleNotFoundError: No module named '_version'
(pod5) [fedora@npavlovikj-dev pod5-file-format]$ 
```

Thank you,
Natasha

**Comment by jorj1988** [comment]
@npavlovikj Its very odd - i can confirm running you commands here seems to work as expected...

Can you try to create and write to the `_version.py` file?

Content should be: ```# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.2.4'
__version_tuple__ = version_tuple = (0, 2, 4)```

**Comment by HalfPhoton** [comment]
@npavlovikj , 

Setuptools_scm had a breaking change for our pipeline and we have to use version 7.1 until we update.

```bash 
pip install --upgrade pip setuptools_scm~=7.1
```

Apologies for the inconvenience caused

**Comment by npavlovikj** [comment]
@HalfPhoton , thank you so much for looking into this and for the proposed solution - I can verify that using `setuptools_scm=7.1` worked and the `_version.py` file was generated.
I am still getting build errors, but I will open another issue for that - this one can be closed.

Thank you,
Natasha

**Comment by HalfPhoton** [comment]
Thank you for getting back to us with confirmation on this - we'll look to improve the documentation in a future release.

Kind regards,
Rich
