### ISSUE TITLE
ModuleNotFoundError: No module named 'lib_pod5.pod5_format_pybind'

### ISSUE THREAD

**Issue by yoeHuuui** [nanoporetech/pod5-file-format#88]
Very good tools! But I try to install from source code, I get error as below, I don't kown how to fix it?
```
$ pod5
Traceback (most recent call last):
  File "/public/home/miniconda3/envs/ont-meth/bin/pod5", line 5, in <module>
    from pod5.tools.main import main
  File "/public/home/pythonlib/pod5-file-format/python/pod5/src/pod5/__init__.py", line 17, in <module>
    from .api_utils import (
  File "/public/home/pythonlib/pod5-file-format/python/pod5/src/pod5/api_utils.py", line 12, in <module>
    from lib_pod5 import format_read_id_to_str, load_read_id_iterable
  File "/public/home/pythonlib/pod5-file-format/python/lib_pod5/src/lib_pod5/__init__.py", line 4, in <module>
    from .pod5_format_pybind import (
ModuleNotFoundError: No module named 'lib_pod5.pod5_format_pybind'
```

The file in ```/public/home/pythonlib/pod5-file-format/python/lib_pod5/src/lib_pod5/src/lib_pod5```
shows below:
```
$ ls
__init__.py  out  pod5_format_pybind.pyi  __pycache__  py.typed  _version.py
```

**Comment by jorj1988** [comment]
Hi @yoeHuuui,

What version of `pod5` are you installing?

What steps have you run to install from source - can you provide us with a step by step?

- George

**Comment by yoeHuuui** [comment]
Apologies for the delayed response! The version is `0.3.0`, but unfortunately, I failed to provide step-by-step instructions for you initially.

I followed the guide available at: https://github.com/nanoporetech/pod5-file-format/blob/0.3.0/docs/docs/install.rst

After running `make`, I executed `pip install -e .` in both the `python/pod5` and `python/lib_pod5` directories.

I can confirm that I have the `libpod5_format.a` file located in `/public/home/pythonlib/pod5-file-format/build/Release/lib`. However, I am missing the Pybind-Cython file named `pod5_format_pybind.cpython-38-x86_64-linux-gnu.so` in the `lib_pod5` directory.

Perhaps, I need guidance on how to generate the `pod5_format_pybind.cpython-38-x86_64-linux-gnu.so`. Your assistance is highly appreciated. Thank you very much!

**Comment by jorj1988** [comment]
Ah, OK.

The instructions dont mention that if you want to build the python development packages you need to set: `-DBUILD_PYTHON_WHEEL=ON` when running cmake.

This will find python development libs and build a wheel.

https://github.com/nanoporetech/pod5-file-format/blob/0.3.0/CMakeLists.txt#L37

Let me know how this goes for you?
- George

**Comment by yoeHuuui** [comment]
Thank you very much! I have fixed the problem!

**Comment by yoeHuuui** [comment]
As our computer cluster directly installs the released wheel, it encountered an error during execution as follows. Therefore, I needed to build from the source code. I have successfully addressed the issue now!
Thanks again!

```
$ pod5 convert fast5 fast5 fast5/*.fast5 --output ./out_pod5/test.pod5
An unexpected error occurred: getrandom
Converting 12 Fast5s:   0%|                                                                      | 0/48000 [00:06<?, ?Reads/s]
POD5 has encountered an error: 'getrandom'

For detailed information set POD5_DEBUG=1'
Converting 12 Fast5s:   0%|    
```

> Ah, OK.
> 
> The instructions dont mention that if you want to build the python development packages you need to set: `-DBUILD_PYTHON_WHEEL=ON` when running cmake.
> 
> This will find python development libs and build a wheel.
> 
> https://github.com/nanoporetech/pod5-file-format/blob/0.3.0/CMakeLists.txt#L37
> 
> Let me know how this goes for you?
> 
> * George
