### ISSUE TITLE
assets are missing in the latest release 

### ISSUE THREAD

**Issue by hiruna72** [nanoporetech/pod5-file-format#90]
Hello,

Could you please attach the compiled binaries/libraries for the [release 0.3.1](https://github.com/nanoporetech/pod5-file-format/releases/tag/0.3.1) as you have done for [release 0.2.4](https://github.com/nanoporetech/pod5-file-format/releases/tag/0.2.4).

Thank you!

**Comment by jorj1988** [comment]
Apologies @hiruna72,

We had network issues as the release happened and this was missed. `0.3.2` is now live, with assets.

- George
