### ISSUE TITLE
Update documentation for subset from inspect reads

### ISSUE THREAD

**Issue by Kirk3gaard** [nanoporetech/pod5-file-format#96]
Hi

This code example does not work : https://github.com/nanoporetech/pod5-file-format/blob/master/python/pod5/README.md#example-subsetting-from-pod5-inspect-reads
```

# Create the csv table from inspect reads
> pod5 inspect reads example.pod5 > table.csv
> pod5 subset example.pod5 --table table.csv --columns well
```

the "--table" option is not available and the text should be "--csv"

Best regards
Rasmus

**Comment by HalfPhoton** [comment]
Hi @Kirk3gaard ,

This works for me:

```bash 
❯ pod5 inspect reads test_data/multi_fast5_zip_v3.pod5  > table.csv
❯ pod5 subset test_data/multi_fast5_zip_v3.pod5 --table table.csv --columns well 
❯ ls *.pod5
well-2.pod5  well-4.pod5
```

Can you give more details on what is not working?

Are you using the most current pod5?

Best regards, 
Rich

**Comment by Kirk3gaard** [comment]
Hi Rich

Appears that there was an old version stuck on one of our servers.... 

Best regards
Rasmus
