### ISSUE TITLE
pod5 inspect to work with multiple pod5s

### ISSUE THREAD

**Issue by Kirk3gaard** [nanoporetech/pod5-file-format#98]
Hi

When running pod5 inspect on a folder with multiple pod5s 

`pod5 inspect reads pod5s/*pod5 > readstable.csv`

 I noticed that the following line occurs once for every pod5 file in the folder

`read_id,channel,well,pore_type,read_number,start_sample,end_reason,median_before,num_samples,byte_count,signal_compression_ratio,num_minknow_events,tracked_scaling,predicted_scaling,num_reads_since_mux_change,time_since_mux_change`

This causes problems with e.g. pod5  subset as the "read_id" is seen as duplicated several times.

Best regards
Rasmus

**Comment by HalfPhoton** [comment]
Hi @Kirk3gaard ,

Is `pod5 view` not suitable for your use case?

Kind regards,
Rich

**Comment by Kirk3gaard** [comment]
Hi Rich

It sure is. And so much faster!!!. Any reason why the inspect is still in the github examples?

Best regards
Rasmus

**Comment by HalfPhoton** [comment]
Good point, we'll remove the examples in favour of `view`
